export const STARTER_TEMPLATE_KINDS = [
  'daily',
  'weeklyReview',
  'meeting',
  'sourceNote',
  'knowledgeMap',
  'calloutLibrary',
  'agentTask',
  'agentReview',
  'taskReview',
  'savedQuery',
  'publishPreflight',
  'savedQueryCatalog',
  'verificationReportWorkflow',
  'implementationPlan',
  'refactorPlan',
  'seoBrief',
  'contentRefreshBrief',
  'research',
  'sprintPlan',
  'productSpec',
  'project',
  'supportTicket',
  'experimentLog',
  'contentOutline',
  'interviewNotes',
  'bugReport',
  'decision',
  'incidentPostmortem',
  'technicalRFC',
  'apiSpec',
  'extensionSpec',
  'launchPlan',
  'customerProfile',
  'contentCalendar',
  'learningPlan',
  'decisionReview',
  'publishPage',
  'publishRunbook',
  'changelog',
  'transcriptCleanup',
  'releaseNotes',
  'person'
] as const
export type StarterTemplateKind = (typeof STARTER_TEMPLATE_KINDS)[number]

export const STARTER_TEMPLATE_CATALOG: { kind: StarterTemplateKind; label: string; detail: string }[] = [
  { kind: 'daily', label: 'Daily note', detail: 'Focus, log, decisions, follow-ups' },
  { kind: 'weeklyReview', label: 'Weekly review', detail: 'Wins, learnings, open loops, next week' },
  { kind: 'meeting', label: 'Meeting notes', detail: 'Agenda, decisions, action items' },
  { kind: 'sourceNote', label: 'Source note', detail: 'Literature notes and source extraction' },
  { kind: 'knowledgeMap', label: 'Knowledge map', detail: 'MOC hub for linked notes and gaps' },
  { kind: 'calloutLibrary', label: 'Callout library / snippets', detail: 'Reusable note, tip, warning, question, and quote snippets' },
  { kind: 'agentTask', label: 'Agent task', detail: 'Precise AI work briefs' },
  { kind: 'agentReview', label: 'Agent review / QA', detail: 'Checklist for reviewing agent work' },
  { kind: 'taskReview', label: 'Task review', detail: 'Review open work, owners, blockers, and next actions' },
  { kind: 'savedQuery', label: 'Saved query', detail: 'Reusable search, task, tag, or link query' },
  { kind: 'publishPreflight', label: 'Publish preflight', detail: 'Readiness checks before static-site publishing' },
  { kind: 'savedQueryCatalog', label: 'Saved query catalog', detail: 'Index reusable queries, thresholds, and owners' },
  { kind: 'verificationReportWorkflow', label: 'Verification report', detail: 'Capture checks, evidence, risks, and handoff' },
  { kind: 'implementationPlan', label: 'Implementation plan', detail: 'Scope, steps, commands, verification, and handoff' },
  { kind: 'refactorPlan', label: 'Refactor plan', detail: 'Preserve behavior while changing structure safely' },
  { kind: 'seoBrief', label: 'SEO/content brief', detail: 'Audience, intent, outline, links' },
  { kind: 'contentRefreshBrief', label: 'Content refresh brief', detail: 'Audit and update stale content without losing intent' },
  { kind: 'research', label: 'Research brief', detail: 'Questions, sources, synthesis' },
  { kind: 'sprintPlan', label: 'Sprint plan', detail: 'Goals, scope, capacity, risks' },
  { kind: 'productSpec', label: 'PRD', detail: 'Requirements and launch criteria' },
  { kind: 'project', label: 'Project plan', detail: 'Scope, milestones, risks' },
  { kind: 'supportTicket', label: 'Support ticket', detail: 'Customer issue tracking and resolution' },
  { kind: 'experimentLog', label: 'Experiment log', detail: 'Hypothesis, procedure, results' },
  { kind: 'contentOutline', label: 'Content outline', detail: 'Structured drafting brief' },
  { kind: 'interviewNotes', label: 'Interview notes', detail: 'Research, customer, or hiring notes' },
  { kind: 'bugReport', label: 'Bug report', detail: 'Repro, impact, fix notes' },
  { kind: 'decision', label: 'Decision record', detail: 'Options, rationale, consequences' },
  { kind: 'incidentPostmortem', label: 'Incident postmortem', detail: 'Impact, timeline, causes, follow-up' },
  { kind: 'technicalRFC', label: 'Technical RFC', detail: 'Proposal, tradeoffs, rollout plan' },
  { kind: 'apiSpec', label: 'API spec', detail: 'Endpoint contract and examples' },
  { kind: 'extensionSpec', label: 'Extension spec', detail: 'Manifest, contribution points, permissions, and QA' },
  { kind: 'launchPlan', label: 'Launch plan', detail: 'Readiness, rollout, comms, metrics' },
  { kind: 'customerProfile', label: 'Customer profile', detail: 'Account context, goals, risks, next steps' },
  { kind: 'contentCalendar', label: 'Content calendar', detail: 'Campaign schedule and publishing workflow' },
  { kind: 'learningPlan', label: 'Learning plan', detail: 'Goals, resources, practice, evidence' },
  { kind: 'decisionReview', label: 'Decision review', detail: 'Evaluate outcomes and next decision' },
  { kind: 'publishPage', label: 'Publish page', detail: 'Public Markdown page draft' },
  { kind: 'publishRunbook', label: 'Publish runbook', detail: 'Repeatable static-site publishing checklist and rollback plan' },
  { kind: 'changelog', label: 'Changelog entry', detail: 'Forge-style product entries' },
  { kind: 'transcriptCleanup', label: 'Transcript cleanup', detail: 'Raw transcript to polished notes' },
  { kind: 'releaseNotes', label: 'Release notes', detail: 'User-facing changes' },
  { kind: 'person', label: 'Person', detail: 'Relationship notes' }
]

export interface StarterTemplateDefinition {
  file: string
  content: string
}

export const STARTER_TEMPLATES: Record<StarterTemplateKind, StarterTemplateDefinition> = {
  daily: {
    file: 'Daily.md',
    content: [
      '---',
      'date: {{date}}',
      'tags: [daily]',
      '---',
      '',
      '# {{date}}',
      '',
      '## Focus',
      '{{prompt:Focus}}',
      '',
      '## Priorities',
      '- [ ] ',
      '- [ ] ',
      '- [ ] ',
      '',
      '## Schedule',
      '- ',
      '',
      '## Notes',
      '',
      '## Decisions',
      '- ',
      '',
      '## Tasks',
      '- [ ] ',
      '',
      '## Follow-ups',
      '- '
    ].join('\n')
  },
  weeklyReview: {
    file: 'Weekly Review.md',
    content: [
      '---',
      'type: weekly-review',
      'week: {{prompt:Week}}',
      'status: {{select:Status|Draft,Reviewed,Archived}}',
      'created: {{date}}',
      'tags: [weekly-review, review]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Week',
      '{{prompt:Week}}',
      '',
      '## Wins',
      '- ',
      '',
      '## Shipped',
      '- ',
      '',
      '## Learned',
      '- ',
      '',
      '## Metrics',
      '- Metric:  Result:  Notes: ',
      '',
      '## Open Loops',
      '- [ ] ',
      '',
      '## Decisions',
      '- ',
      '',
      '## Next Week',
      '- Focus:',
      '- Risks:',
      '- First action:',
      '',
      '## Agent Follow-up',
      '- Notes to summarize:',
      '- Links to repair:',
      '- Tasks to extract:'
    ].join('\n')
  },
  meeting: {
    file: 'Meeting Notes.md',
    content: [
      '---',
      'type: meeting',
      'date: {{date}}',
      'status: {{select:Status|Scheduled,In progress,Done}}',
      'tags: [meeting]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Attendees',
      '{{prompt:Attendees}}',
      '',
      '## Agenda',
      '{{prompt:Agenda}}',
      '',
      '## Notes',
      '',
      '## Decisions',
      '- ',
      '',
      '## Action Items',
      '- [ ] Owner:  Due:  Task: ',
      '',
      '## Follow-ups',
      '- '
    ].join('\n')
  },
  sourceNote: {
    file: 'Source Note.md',
    content: [
      '---',
      'type: source-note',
      'source_type: {{select:Source type|Book,Article,Paper,Podcast,Video,Docs,Other}}',
      'status: {{select:Status|Queued,Reading,Processed,Archived}}',
      'author: {{prompt:Author}}',
      'source: {{prompt:Source}}',
      'url: {{prompt:URL}}',
      'created: {{date}}',
      'tags: [source, literature]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Citation',
      '- Author: {{prompt:Author}}',
      '- Source: {{prompt:Source}}',
      '- URL: {{prompt:URL}}',
      '',
      '## Why This Matters',
      '{{prompt:Why this matters}}',
      '',
      '## Summary',
      '',
      '## Key Ideas',
      '- Idea:  Evidence:  Confidence: ',
      '',
      '## Quotes',
      '- ',
      '',
      '## Connections',
      '- Related notes: ',
      '- Contradicts: ',
      '- Supports: ',
      '',
      '## Questions',
      '- ',
      '',
      '## Agent Extraction Tasks',
      '- [ ] Pull durable claims into evergreen notes',
      '- [ ] Link people, organizations, and concepts',
      '- [ ] Flag uncertain or unsupported claims'
    ].join('\n')
  },
  knowledgeMap: {
    file: 'Knowledge Map.md',
    content: [
      '---',
      'type: knowledge-map',
      'topic: {{prompt:Topic}}',
      'status: {{select:Status|Draft,Living,Archived}}',
      'created: {{date}}',
      'tags: [moc, map]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Purpose',
      '{{prompt:Purpose}}',
      '',
      '## Core Notes',
      '- [[ ]]',
      '',
      '## Clusters',
      '### People',
      '- ',
      '',
      '### Concepts',
      '- ',
      '',
      '### Projects',
      '- ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Gaps',
      '- Missing note:',
      '- Stale note:',
      '- Broken link:',
      '',
      '## Next Links to Create',
      '- [[ ]]',
      '',
      '## Agent Maintenance',
      '- [ ] Find unlinked mentions for this topic',
      '- [ ] Suggest notes that belong in this map',
      '- [ ] Summarize changes since last review'
    ].join('\n')
  },
  calloutLibrary: {
    file: 'Callout Library.md',
    content: [
      '---',
      'type: callout-library',
      'status: {{select:Status|Draft,Active,Archived}}',
      'created: {{date}}',
      'tags: [callouts, templates]',
      '---',
      '',
      '# {{title}}',
      '',
      '## How to Use',
      '- Copy a snippet into any note.',
      '- Replace placeholder text with the actual context.',
      '- Keep callouts short enough to scan.',
      '',
      '## Note',
      '> [!note] Context',
      '> Use this for neutral background, definitions, or source notes.',
      '',
      '## Tip',
      '> [!tip] Better Path',
      '> Use this for a recommended action, shortcut, or pattern.',
      '',
      '## Warning',
      '> [!warning] Check Before Shipping',
      '> Use this for risks, blockers, caveats, or destructive steps.',
      '',
      '## Question',
      '> [!question] Open Question',
      '> Use this for unresolved decisions, research prompts, or agent follow-up.',
      '',
      '## Quote',
      '> [!quote] Source Quote',
      '> Use this for copied source text that needs attribution.',
      '> Source: {{prompt:Source}}',
      '',
      '## Agent Notes',
      '- Preserve callout type and title when rewriting notes.',
      '- Do not convert warnings into neutral notes.',
      '- Keep quoted text attributed to its source.'
    ].join('\n')
  },
  project: {
    file: 'Project Plan.md',
    content: [
      '---',
      'type: project-plan',
      'status: {{select:Status|Planning,Active,Paused,Done}}',
      'owner: {{prompt:Owner}}',
      'target: {{prompt:Target date}}',
      'tags: [project]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goal',
      '{{prompt:Goal}}',
      '',
      '## Background',
      '',
      '## Scope',
      '### In scope',
      '- ',
      '',
      '### Out of scope',
      '- ',
      '',
      '## Deliverables',
      '- ',
      '',
      '## Milestones',
      '- [ ] Milestone:  Owner:  Date: ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Next Actions',
      '- [ ] '
    ].join('\n')
  },
  person: {
    file: 'Person.md',
    content: [
      '---',
      'type: person',
      'tags: [person]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Role',
      '{{prompt:Role}}',
      '',
      '## Context',
      '',
      '## Notes',
      '',
      '## Follow-ups',
      ''
    ].join('\n')
  },
  research: {
    file: 'Research Brief.md',
    content: [
      '---',
      'type: research-brief',
      'status: {{select:Status|Scoping,Researching,Synthesizing,Done}}',
      'created: {{date}}',
      'tags: [research]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Research Question',
      '{{prompt:Research question}}',
      '',
      '## Decision or Use',
      '{{prompt:Decision or use}}',
      '',
      '## Source List',
      '- Source:  Why it matters: ',
      '',
      '## Findings',
      '- Finding:  Evidence:  Confidence: ',
      '',
      '## Synthesis',
      '',
      '## Risks and Gaps',
      '- ',
      '',
      '## Recommended Next Step',
      ''
    ].join('\n')
  },
  sprintPlan: {
    file: 'Sprint Plan.md',
    content: [
      '---',
      'type: sprint-plan',
      'sprint: {{prompt:Sprint}}',
      'status: {{select:Status|Planned,Active,Complete,Closed}}',
      'start: {{prompt:Start date}}',
      'end: {{prompt:End date}}',
      'created: {{date}}',
      'tags: [sprint, planning]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Sprint Goal',
      '{{prompt:Sprint goal}}',
      '',
      '## Capacity',
      '- People:',
      '- Focus days:',
      '- Known interruptions:',
      '',
      '## Commitments',
      '- [ ] Owner:  Work:  Done when: ',
      '',
      '## Backlog Candidates',
      '- ',
      '',
      '## Execution Plan',
      '### Now',
      '- ',
      '',
      '### Next',
      '- ',
      '',
      '### Blocked',
      '- ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Review Criteria',
      '- Demo:',
      '- Metrics:',
      '- Retro notes:',
      '',
      '## Agent Tasks',
      '- [ ] Break commitments into implementation tasks',
      '- [ ] Check linked specs and issues for stale assumptions',
      '- [ ] Draft end-of-sprint summary'
    ].join('\n')
  },
  agentTask: {
    file: 'Agent Task Brief.md',
    content: [
      '---',
      'type: agent-task',
      'status: {{select:Status|Ready,In progress,Blocked,Done}}',
      'created: {{date}}',
      'tags: [agent, task]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Context',
      '- Vault: {{vault}}',
      '- Folder: {{folder}}',
      '- Related notes: {{prompt:Related notes}}',
      '',
      '## Constraints',
      '- Preserve existing user changes.',
      '- Keep paths relative to the vault.',
      '- Stay within the requested ownership boundary.',
      '- Prefer small, reviewable edits.',
      '',
      '## Inputs',
      '- Files or folders: {{prompt:Files or folders}}',
      '- External references: {{prompt:External references}}',
      '',
      '## Definition of Done',
      '- [ ] Requested change is complete',
      '- [ ] Targeted validation has run or is explained',
      '- [ ] Files changed are summarized',
      '',
      '## Checklist',
      '- [ ] Inspect current state',
      '- [ ] Implement the requested change',
      '- [ ] Verify behavior',
      '- [ ] Summarize outcome',
      '',
      '## Verification',
      '',
      '## Result',
      ''
    ].join('\n')
  },
  agentReview: {
    file: 'Agent Review QA.md',
    content: [
      '---',
      'type: agent-review',
      'status: {{select:Status|Ready,Reviewing,Changes requested,Approved,Blocked}}',
      'reviewer: {{prompt:Reviewer}}',
      'created: {{date}}',
      'tags: [agent, review, qa]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Scope',
      '- Request: {{prompt:Request}}',
      '- Files or notes reviewed: {{prompt:Files or notes reviewed}}',
      '- Ownership boundary:',
      '- Out of scope:',
      '',
      '## Review Checklist',
      '- [ ] Requested behavior is implemented',
      '- [ ] Unrelated edits are not included',
      '- [ ] Markdown renders cleanly',
      '- [ ] Links, tags, and frontmatter are valid',
      '- [ ] Agent-facing instructions are clear',
      '- [ ] Validation output is captured or explained',
      '',
      '## Findings',
      '- Severity:',
      '- Location:',
      '- Issue:',
      '- Recommendation:',
      '',
      '## Callouts to Add',
      '> [!warning] Risk',
      '> Note any risky follow-up or unresolved blocker.',
      '',
      '> [!question] Open Question',
      '> Note anything that needs user or owner input.',
      '',
      '## QA Notes',
      '',
      '## Decision',
      '{{select:Decision|Approve,Request changes,Block,Needs owner review}}',
      '',
      '## Follow-up Tasks',
      '- [ ] '
    ].join('\n')
  },
  taskReview: {
    file: 'Task Review.md',
    content: [
      '---',
      'type: task-review',
      'status: {{select:Status|Ready,Reviewing,Done}}',
      'period: {{prompt:Review period}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [tasks, review]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Scope',
      '- Review period: {{prompt:Review period}}',
      '- Folder or project: {{prompt:Folder or project}}',
      '- Owner: {{prompt:Owner}}',
      '',
      '## Summary',
      '- Open tasks:',
      '- Completed tasks:',
      '- Blocked tasks:',
      '- Deferred tasks:',
      '',
      '## Needs Attention',
      '| Task | Owner | Source note | Reason | Next step |',
      '| --- | --- | --- | --- | --- |',
      '|  |  |  |  |  |',
      '',
      '## Completed',
      '- [x] ',
      '',
      '## Blocked',
      '- [ ] Owner:  Blocker:  Decision needed: ',
      '',
      '## Deferred or Dropped',
      '- Task:  Reason: ',
      '',
      '## Next Actions',
      '- [ ] Owner:  Due:  Action: ',
      '',
      '## Agent Review Instructions',
      '- Group duplicate tasks before recommending owners.',
      '- Preserve source-note links for every migrated task.',
      '- Flag stale tasks that have no owner or next step.'
    ].join('\n')
  },
  savedQuery: {
    file: 'Saved Query.md',
    content: [
      '---',
      'type: saved-query',
      'query_type: {{select:Query type|Search,Task,Tag,Link,Vault health,Publish}}',
      'status: {{select:Status|Draft,Active,Paused,Archived}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [query, saved]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Purpose',
      '{{prompt:Purpose}}',
      '',
      '## Query',
      '- Type: {{select:Query type|Search,Task,Tag,Link,Vault health,Publish}}',
      '- Search text or filter: {{prompt:Search text or filter}}',
      '- Folder scope: {{prompt:Folder scope}}',
      '- Sort or grouping:',
      '',
      '## Command or Steps',
      '```bash',
      'forge --vault "{{vault}}" search "{{prompt:Search text or filter}}" --json',
      '```',
      '',
      '## Expected Results',
      '- Signal:',
      '- Healthy range:',
      '- Action threshold:',
      '',
      '## Review Cadence',
      '- Cadence: {{select:Cadence|Daily,Weekly,Monthly,Before publish,As needed}}',
      '- Owner: {{prompt:Owner}}',
      '',
      '## Results Log',
      '- {{date}} - Result:  Action:',
      '',
      '## Agent Notes',
      '- Keep the query narrow enough to act on.',
      '- Record false positives so future runs can refine the filter.',
      '- Link follow-up notes created from this query.'
    ].join('\n')
  },
  publishPreflight: {
    file: 'Publish Preflight.md',
    content: [
      '---',
      'type: publish-preflight',
      'category: publish',
      'status: {{select:Status|Draft,Checking,Ready,Blocked,Published}}',
      'target: {{prompt:Publish target}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [publish, preflight, agent]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Scope',
      '- Vault: {{vault}}',
      '- Publish target: {{prompt:Publish target}}',
      '- Owned files: {{prompt:Owned files}}',
      '- Output directory:',
      '- Out of scope:',
      '',
      '## Allowed Commands',
      '```bash',
      'forge --vault "{{vault}}" analyze --json',
      'forge --vault "{{vault}}" publish --out "{{prompt:Publish target}}" --clean --json',
      '```',
      '',
      '## Preflight Checklist',
      '- [ ] Required pages have titles, slugs, and descriptions',
      '- [ ] Draft or private pages are excluded or approved',
      '- [ ] Broken wikilinks are resolved or accepted',
      '- [ ] Image, video, PDF, and attachment references are present',
      '- [ ] Navigation, tags, and index pages are reviewed',
      '- [ ] Release notes or publish notes are ready',
      '- [ ] Output directory and clean behavior are confirmed',
      '',
      '## Findings',
      '| Area | Finding | Source | Required action | Owner |',
      '| --- | --- | --- | --- | --- |',
      '| Links |  |  |  | {{prompt:Owner}} |',
      '',
      '## Publish Decision',
      '{{select:Decision|Ready to publish,Publish with notes,Blocked,Needs owner review}}',
      '',
      '## Verification',
      '- Analyze result:',
      '- Publish result:',
      '- Pages generated:',
      '- Broken links remaining:',
      '- Assets checked:',
      '',
      '## Risks',
      '- Risk:  Mitigation:',
      '',
      '## Final Handoff Notes',
      '- Published output:',
      '- Blockers:',
      '- Follow-up owners:',
      '- Next publish window:'
    ].join('\n')
  },
  savedQueryCatalog: {
    file: 'Saved Query Catalog.md',
    content: [
      '---',
      'type: saved-query-catalog',
      'category: query',
      'status: {{select:Status|Draft,Active,Review,Archived}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [query, catalog, agent]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Scope',
      '- Vault: {{vault}}',
      '- Folder or collection: {{prompt:Folder or collection}}',
      '- Owned files: {{prompt:Owned files}}',
      '- Out of scope:',
      '',
      '## Allowed Commands',
      '```bash',
      'forge --vault "{{vault}}" search "{{prompt:Search text}}" --json',
      'forge --vault "{{vault}}" analyze --json',
      '```',
      '',
      '## Catalog',
      '| Name | Type | Query or command | Cadence | Owner | Action threshold |',
      '| --- | --- | --- | --- | --- | --- |',
      '|  | {{select:Query type|Search,Task,Tag,Link,Vault health,Publish}} |  | {{select:Cadence|Daily,Weekly,Monthly,Before publish,As needed}} | {{prompt:Owner}} |  |',
      '',
      '## Query Details',
      '### {{prompt:Query name}}',
      '- Purpose:',
      '- Search text or filter: {{prompt:Search text}}',
      '- Expected healthy result:',
      '- False positives to ignore:',
      '- Follow-up note or queue:',
      '',
      '## Agent Checklist',
      '- [ ] Remove duplicate or stale saved queries',
      '- [ ] Add owner, cadence, and threshold to every active query',
      '- [ ] Link each query to the workflow it supports',
      '- [ ] Record example output for ambiguous filters',
      '',
      '## Verification',
      '- Commands run:',
      '- Queries tested:',
      '- Broken or noisy queries:',
      '- Catalog changes:',
      '',
      '## Risks',
      '- Risk:  Mitigation:',
      '',
      '## Final Handoff Notes',
      '- Added:',
      '- Updated:',
      '- Archived:',
      '- Needs owner decision:'
    ].join('\n')
  },
  verificationReportWorkflow: {
    file: 'Verification Report.md',
    content: [
      '---',
      'type: verification-report',
      'category: verification',
      'status: {{select:Status|Draft,Verifying,Passed,Failed,Blocked}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [verification, agent]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Work Reviewed',
      '- Request or plan: {{prompt:Request or plan}}',
      '- Owned files: {{prompt:Owned files}}',
      '- Out of scope:',
      '- Reviewer: {{prompt:Owner}}',
      '',
      '## Allowed Commands',
      '```bash',
      '{{prompt:Allowed verification command}}',
      '```',
      '',
      '## Verification Matrix',
      '| Check | Command or method | Expected | Actual | Status |',
      '| --- | --- | --- | --- | --- |',
      '|  |  |  |  | Pending |',
      '',
      '## Evidence',
      '- Output summary:',
      '- Files inspected:',
      '- Screenshots or artifacts:',
      '- Manual checks:',
      '',
      '## Agent Checklist',
      '- [ ] Verify the requested behavior, not just command success',
      '- [ ] Confirm no unrelated files were changed',
      '- [ ] Capture failures with exact commands and next steps',
      '- [ ] Re-check after fixes if any verification failed',
      '',
      '## Risks',
      '- Risk:  Mitigation:',
      '',
      '## Final Handoff Notes',
      '- Result: {{select:Result|Pass,Pass with caveats,Fail,Blocked}}',
      '- Changed files reviewed:',
      '- Tests or checks not run:',
      '- Follow-up required:'
    ].join('\n')
  },
  implementationPlan: {
    file: 'Implementation Plan.md',
    content: [
      '---',
      'type: implementation-plan',
      'category: plan',
      'status: {{select:Status|Draft,Ready,In progress,Blocked,Done}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [implementation, plan, agent]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Context',
      '- Vault: {{vault}}',
      '- Related notes: {{prompt:Related notes}}',
      '- Current behavior:',
      '- Desired behavior:',
      '',
      '## Ownership Boundary',
      '- Owned files: {{prompt:Owned files}}',
      '- Do not touch:',
      '- Dependencies:',
      '- Out of scope:',
      '',
      '## Allowed Commands',
      '```bash',
      '{{prompt:Allowed command}}',
      '```',
      '',
      '## Plan',
      '- [ ] Inspect current state and existing dirty changes',
      '- [ ] Identify the smallest behavior-preserving change',
      '- [ ] Implement in scoped files',
      '- [ ] Update related docs or templates',
      '- [ ] Run targeted verification',
      '- [ ] Summarize changed files and residual risks',
      '',
      '## Acceptance Criteria',
      '- [ ] User-facing requirement is met',
      '- [ ] Existing workflows still work',
      '- [ ] Edge cases are covered or documented',
      '- [ ] Handoff notes are specific enough for review',
      '',
      '## Verification',
      '- Commands to run:',
      '- Expected output:',
      '- Manual checks:',
      '- Not covered:',
      '',
      '## Risks',
      '- Risk:  Mitigation:',
      '',
      '## Final Handoff Notes',
      '- Completed:',
      '- Changed files:',
      '- Verification result:',
      '- Follow-up:'
    ].join('\n')
  },
  refactorPlan: {
    file: 'Refactor Plan.md',
    content: [
      '---',
      'type: refactor-plan',
      'category: plan',
      'status: {{select:Status|Draft,Ready,In progress,Blocked,Done}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [refactor, plan, agent]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Behavior to Preserve',
      '- User-visible behavior:',
      '- Data or file format:',
      '- Public commands or APIs:',
      '- Known edge cases:',
      '',
      '## Ownership Boundary',
      '- Owned files: {{prompt:Owned files}}',
      '- Do not touch:',
      '- Dependencies:',
      '- Out of scope:',
      '',
      '## Allowed Commands',
      '```bash',
      '{{prompt:Allowed command}}',
      '```',
      '',
      '## Refactor Steps',
      '- [ ] Characterize current behavior with tests or examples',
      '- [ ] Split mechanical moves from behavior changes',
      '- [ ] Make one small structural change at a time',
      '- [ ] Keep names and interfaces stable unless approved',
      '- [ ] Run verification after each risky step',
      '- [ ] Remove dead paths only when usage is checked',
      '',
      '## Verification',
      '- Baseline command output:',
      '- Post-refactor command output:',
      '- Manual regression checks:',
      '- Performance or size checks:',
      '',
      '## Risks',
      '- Risk:  Mitigation:',
      '- Rollback path:',
      '',
      '## Final Handoff Notes',
      '- Behavior preserved:',
      '- Structure changed:',
      '- Tests or checks run:',
      '- Follow-up refactors:'
    ].join('\n')
  },
  seoBrief: {
    file: 'SEO Content Brief.md',
    content: [
      '---',
      'type: seo-brief',
      'status: {{select:Status|Brief,Drafting,Review,Published}}',
      'content_type: {{select:Content type|Article,Landing page,Docs,Case study,Email}}',
      'created: {{date}}',
      'tags: [seo, content]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Search Target',
      '- Primary keyword: {{prompt:Primary keyword}}',
      '- Secondary keywords: {{prompt:Secondary keywords}}',
      '- Search intent: {{select:Search intent|Informational,Commercial,Transactional,Navigational}}',
      '',
      '## Angle',
      '{{prompt:Angle}}',
      '',
      '## Reader Promise',
      '',
      '## Outline',
      '- H1: {{title}}',
      '- H2:',
      '- H2:',
      '- H2:',
      '',
      '## Evidence and Sources',
      '- ',
      '',
      '## Internal Links',
      '- ',
      '',
      '## Meta',
      '- Title tag:',
      '- Description:',
      '- Slug:',
      '',
      '## Notes for Agent',
      '- Preserve factual uncertainty.',
      '- Suggest sources before drafting claims.',
      '- Keep headings scannable.',
      ''
    ].join('\n')
  },
  contentRefreshBrief: {
    file: 'Content Refresh Brief.md',
    content: [
      '---',
      'type: content-refresh-brief',
      'status: {{select:Status|Audit,Refreshing,Review,Published}}',
      'asset_type: {{select:Asset type|Article,Docs,Landing page,Guide,Newsletter,Video}}',
      'owner: {{prompt:Owner}}',
      'url: {{prompt:URL}}',
      'created: {{date}}',
      'tags: [content, refresh]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Existing Asset',
      '- URL or note: {{prompt:URL}}',
      '- Asset type: {{select:Asset type|Article,Docs,Landing page,Guide,Newsletter,Video}}',
      '- Current owner: {{prompt:Owner}}',
      '- Last updated:',
      '',
      '## Refresh Goal',
      '{{prompt:Refresh goal}}',
      '',
      '## Audience and Intent',
      '- Audience: {{prompt:Audience}}',
      '- Search or reader intent:',
      '- Conversion or next action:',
      '',
      '## Decay Signals',
      '- Outdated claim:',
      '- Broken link:',
      '- Missing section:',
      '- Performance signal:',
      '',
      '## Updates Needed',
      '- Keep:',
      '- Rewrite:',
      '- Add:',
      '- Remove:',
      '',
      '## Source Review',
      '- Source:  Claim supported:  Notes: ',
      '',
      '## SEO and Distribution',
      '- Primary keyword:',
      '- Internal links to add:',
      '- Channels to re-share:',
      '',
      '## QA Checklist',
      '- [ ] Facts and dates checked',
      '- [ ] Links checked',
      '- [ ] Title and description updated',
      '- [ ] Publish or changelog note prepared',
      '',
      '## Agent Drafting Notes',
      '- Preserve the original audience and promise unless the brief changes them.',
      '- Mark unsupported claims instead of rewriting them as fact.',
      '- Summarize material changes for reviewers.'
    ].join('\n')
  },
  productSpec: {
    file: 'PRD.md',
    content: [
      '---',
      'type: prd',
      'status: {{select:Status|Draft,Review,Ready,Building,Shipped}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [product, prd]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Problem',
      '{{prompt:Problem}}',
      '',
      '## Users',
      '{{prompt:Users}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Non-goals',
      '- ',
      '',
      '## Requirements',
      '- Must:',
      '- Should:',
      '- Could:',
      '',
      '## User Experience',
      '- Entry point:',
      '- Primary flow:',
      '- Empty/error states:',
      '',
      '## Data and Instrumentation',
      '- Events:',
      '- Success metrics:',
      '- Guardrails:',
      '',
      '## Rollout Plan',
      '- ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Launch Checklist',
      '- [ ] Product review',
      '- [ ] Engineering review',
      '- [ ] Support/docs ready',
      ''
    ].join('\n')
  },
  supportTicket: {
    file: 'Support Ticket.md',
    content: [
      '---',
      'type: support-ticket',
      'status: {{select:Status|New,Waiting on customer,Investigating,Resolved,Closed}}',
      'priority: {{select:Priority|Low,Normal,High,Urgent}}',
      'customer: {{prompt:Customer}}',
      'created: {{date}}',
      'tags: [support]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Customer Context',
      '- Customer: {{prompt:Customer}}',
      '- Plan/account:',
      '- Related notes:',
      '',
      '## Timeline',
      '- {{datetime}} - Created',
      '',
      '## Reproduction',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Expected',
      '',
      '## Actual',
      '',
      '## Workaround',
      '',
      '## Resolution',
      '',
      '## Follow-up',
      '- [ ] Reply to customer',
      '- [ ] Update docs or saved reply',
      '- [ ] Link related bug or decision'
    ].join('\n')
  },
  experimentLog: {
    file: 'Experiment Log.md',
    content: [
      '---',
      'type: experiment-log',
      'status: {{select:Status|Proposed,Running,Analyzing,Concluded}}',
      'owner: {{prompt:Owner}}',
      'started: {{date}}',
      'tags: [experiment]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Hypothesis',
      '{{prompt:Hypothesis}}',
      '',
      '## Success Criteria',
      '- ',
      '',
      '## Variables',
      '- Independent:',
      '- Dependent:',
      '- Controls:',
      '',
      '## Setup',
      '',
      '## Procedure',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Observations',
      '- ',
      '',
      '## Data',
      '- Source:',
      '- Result:',
      '',
      '## Conclusion',
      '',
      '## Decision',
      '{{select:Decision|Keep,Iterate,Stop,Inconclusive}}',
      '',
      '## Follow-up',
      '- [ ] '
    ].join('\n')
  },
  contentOutline: {
    file: 'Content Outline.md',
    content: [
      '---',
      'type: content-outline',
      'status: {{select:Status|Outline,Drafting,Review,Published}}',
      'format: {{select:Format|Article,Guide,Newsletter,Video,Talk,Thread}}',
      'audience: {{prompt:Audience}}',
      'created: {{date}}',
      'tags: [content, outline]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goal',
      '{{prompt:Goal}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Reader Promise',
      '',
      '## Angle',
      '{{prompt:Angle}}',
      '',
      '## Outline',
      '- H1: {{title}}',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '',
      '## Evidence and Links',
      '- ',
      '',
      '## Distribution Notes',
      '- Channel:',
      '- CTA:',
      '',
      '## Agent Drafting Notes',
      '- Preserve claims that need citations.',
      '- Keep examples concrete.',
      '- Do not fill gaps with invented facts.'
    ].join('\n')
  },
  interviewNotes: {
    file: 'Interview Notes.md',
    content: [
      '---',
      'type: interview-notes',
      'interview_type: {{select:Interview type|User research,Candidate,Customer,Expert,Internal}}',
      'participant: {{prompt:Participant}}',
      'date: {{date}}',
      'status: {{select:Status|Scheduled,Completed,Synthesized,Archived}}',
      'tags: [interview]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Participant Context',
      '- Name: {{prompt:Participant}}',
      '- Role/context:',
      '- Related notes:',
      '',
      '## Questions',
      '- ',
      '',
      '## Notes',
      '',
      '## Highlights',
      '- ',
      '',
      '## Pain Points',
      '- ',
      '',
      '## Quotes',
      '- ',
      '',
      '## Opportunities',
      '- ',
      '',
      '## Follow-ups',
      '- [ ] ',
      '',
      '## Agent Synthesis Instructions',
      '- Separate observation from interpretation.',
      '- Preserve exact quotes only when recorded.',
      '- Link themes back to source notes.'
    ].join('\n')
  },
  bugReport: {
    file: 'Bug Report.md',
    content: [
      '---',
      'type: bug',
      "status: {{select:Status|New,Triaged,Fixing,Fixed,Won't fix}}",
      'severity: {{select:Severity|Low,Medium,High,Critical}}',
      'created: {{date}}',
      'tags: [bug]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Impact',
      '{{prompt:Impact}}',
      '',
      '## Environment',
      '{{prompt:Environment}}',
      '',
      '## Steps to Reproduce',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Expected',
      '',
      '## Actual',
      '',
      '## Suspected Cause',
      '',
      '## Workaround',
      '',
      '## Notes / Fix',
      ''
    ].join('\n')
  },
  decision: {
    file: 'Decision Record.md',
    content: [
      '---',
      'type: decision-record',
      'status: {{select:Status|Proposed,Accepted,Rejected,Superseded}}',
      'date: {{date}}',
      'tags: [decision]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Decision',
      '{{prompt:Decision}}',
      '',
      '## Context',
      '',
      '## Options',
      '- Option A:',
      '- Option B:',
      '',
      '## Rationale',
      '',
      '## Consequences',
      '- ',
      '',
      '## Review Date',
      '{{prompt:Review date}}',
      ''
    ].join('\n')
  },
  incidentPostmortem: {
    file: 'Incident Postmortem.md',
    content: [
      '---',
      'type: incident-postmortem',
      'status: {{select:Status|Draft,Reviewed,Closed}}',
      'severity: {{select:Severity|SEV1,SEV2,SEV3,SEV4}}',
      'incident_date: {{prompt:Incident date}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [incident, postmortem]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Impact',
      '- Users affected:',
      '- Duration:',
      '- Systems:',
      '- Customer impact:',
      '',
      '## Timeline',
      '- {{datetime}} - Detected',
      '-  - Mitigated',
      '-  - Resolved',
      '',
      '## Detection',
      '- Signal:',
      '- Alert or report:',
      '- Time to detect:',
      '',
      '## Root Cause',
      '- Trigger:',
      '- Contributing factors:',
      '- What changed:',
      '',
      '## Resolution',
      '- Mitigation:',
      '- Permanent fix:',
      '- Verification:',
      '',
      '## What Went Well',
      '- ',
      '',
      '## What Went Wrong',
      '- ',
      '',
      '## Follow-up Actions',
      '- [ ] Owner:  Due:  Action: ',
      '',
      '## Agent Tasks',
      '- [ ] Extract action items with owners and due dates',
      '- [ ] Link related support tickets, bugs, and decisions',
      '- [ ] Draft customer-facing summary if needed'
    ].join('\n')
  },
  technicalRFC: {
    file: 'Technical RFC.md',
    content: [
      '---',
      'type: technical-rfc',
      'status: {{select:Status|Draft,In review,Accepted,Rejected,Implemented}}',
      'owner: {{prompt:Owner}}',
      'reviewers: {{prompt:Reviewers}}',
      'created: {{date}}',
      'tags: [rfc, engineering]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Problem',
      '{{prompt:Problem}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Non-goals',
      '- ',
      '',
      '## Proposed Design',
      '- Architecture:',
      '- Data model:',
      '- User or developer flow:',
      '',
      '## Alternatives Considered',
      '- Option:  Pros:  Cons: ',
      '',
      '## Tradeoffs',
      '- Benefit:',
      '- Cost:',
      '- Risk:',
      '',
      '## Rollout Plan',
      '- Phase:',
      '- Migration:',
      '- Rollback:',
      '',
      '## Observability',
      '- Metrics:',
      '- Logs:',
      '- Alerts:',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Decision Log',
      '- {{date}} - ',
      '',
      '## Agent Review Notes',
      '- [ ] Check assumptions against linked specs or code',
      '- [ ] Identify missing edge cases and migration risks',
      '- [ ] Summarize unresolved reviewer questions'
    ].join('\n')
  },
  apiSpec: {
    file: 'API Spec.md',
    content: [
      '---',
      'type: api-spec',
      'status: {{select:Status|Draft,Review,Stable,Deprecated}}',
      'method: {{select:Method|GET,POST,PUT,PATCH,DELETE}}',
      'endpoint: {{prompt:Endpoint}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [api, spec]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Overview',
      '{{prompt:Overview}}',
      '',
      '## Endpoint',
      '- Method: {{select:Method|GET,POST,PUT,PATCH,DELETE}}',
      '- Path: {{prompt:Endpoint}}',
      '- Auth: {{select:Auth|None,API key,OAuth,Session,Service token}}',
      '',
      '## Request Parameters',
      '| Name | Type | Required | Description |',
      '| --- | --- | --- | --- |',
      '|  |  |  |  |',
      '',
      '## Request Body',
      '```json',
      '{}',
      '```',
      '',
      '## Response',
      '```json',
      '{}',
      '```',
      '',
      '## Error Cases',
      '| Status | Code | Condition | Recovery |',
      '| --- | --- | --- | --- |',
      '|  |  |  |  |',
      '',
      '## Examples',
      '```bash',
      'curl ',
      '```',
      '',
      '## Compatibility',
      '- Versioning:',
      '- Breaking changes:',
      '- Deprecation plan:',
      '',
      '## Test Cases',
      '- [ ] Happy path',
      '- [ ] Auth failure',
      '- [ ] Validation failure',
      '- [ ] Rate limit or quota behavior',
      '',
      '## Agent Tasks',
      '- [ ] Generate example requests and responses',
      '- [ ] Compare implementation behavior with this contract',
      '- [ ] Flag undocumented fields or status codes'
    ].join('\n')
  },
  extensionSpec: {
    file: 'Extension Spec.md',
    content: [
      '---',
      'type: extension-spec',
      'status: {{select:Status|Draft,Review,Ready,Building,Shipped}}',
      'extension_id: {{prompt:Extension ID}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [extension, spec]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Purpose',
      '{{prompt:Purpose}}',
      '',
      '## User Workflow',
      '- Entry point:',
      '- Primary action:',
      '- Success state:',
      '- Empty or error state:',
      '',
      '## Manifest',
      '- Extension ID: {{prompt:Extension ID}}',
      '- Display name:',
      '- Categories:',
      '- Keywords:',
      '- Default installed: {{select:Default installed|No,Yes}}',
      '- Default enabled: {{select:Default enabled|No,Yes}}',
      '',
      '## Extension Points',
      '| Point | Contribution | User-facing label | Notes |',
      '| --- | --- | --- | --- |',
      '|  |  |  |  |',
      '',
      '## Permissions',
      '| Permission | Reason | Data touched |',
      '| --- | --- | --- |',
      '|  |  |  |',
      '',
      '## Settings',
      '- Setting:  Type:  Default:  Validation: ',
      '',
      '## Data and Compatibility',
      '- Reads:',
      '- Writes:',
      '- Migration or fallback:',
      '',
      '## QA Plan',
      '- [ ] Manifest validates',
      '- [ ] Disabled state tested',
      '- [ ] Empty vault behavior tested',
      '- [ ] Permission copy reviewed',
      '- [ ] Agent catalog fallback stays in sync',
      '',
      '## Rollout',
      '- Release note:',
      '- Docs:',
      '- Changelog:',
      '',
      '## Agent Implementation Notes',
      '- Keep extension IDs stable and namespaced.',
      '- Avoid adding runtime permissions unless the workflow requires them.',
      '- Update renderer and agent fallback catalogs together.'
    ].join('\n')
  },
  launchPlan: {
    file: 'Launch Plan.md',
    content: [
      '---',
      'type: launch-plan',
      'status: {{select:Status|Planning,Ready,Launching,Launched,Paused}}',
      'owner: {{prompt:Owner}}',
      'launch_date: {{prompt:Launch date}}',
      'audience: {{prompt:Audience}}',
      'created: {{date}}',
      'tags: [launch, go-to-market]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Scope',
      '### Included',
      '- ',
      '',
      '### Excluded',
      '- ',
      '',
      '## Launch Criteria',
      '- Product:',
      '- Docs:',
      '- Support:',
      '- Analytics:',
      '',
      '## Rollout Plan',
      '- Phase:  Audience:  Date:  Owner: ',
      '',
      '## Communications',
      '- Internal:',
      '- Customer:',
      '- Website or docs:',
      '- Social or community:',
      '',
      '## Support Readiness',
      '- Saved replies:',
      '- Known issues:',
      '- Escalation path:',
      '',
      '## Metrics',
      '- Success metric:',
      '- Guardrail metric:',
      '- Review date:',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Checklist',
      '- [ ] Launch owner assigned',
      '- [ ] Rollback or pause plan written',
      '- [ ] Docs and support notes reviewed',
      '- [ ] Metrics dashboard or query ready',
      '',
      '## Agent Tasks',
      '- [ ] Draft announcement copy from scope and audience',
      '- [ ] Check linked PRD, RFC, and support notes for gaps',
      '- [ ] Summarize launch readiness blockers'
    ].join('\n')
  },
  customerProfile: {
    file: 'Customer Profile.md',
    content: [
      '---',
      'type: customer-profile',
      'status: {{select:Status|Prospect,Active,At risk,Churned,Archived}}',
      'customer: {{prompt:Customer}}',
      'segment: {{select:Segment|Individual,SMB,Mid-market,Enterprise,Internal}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [customer, profile]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Snapshot',
      '- Customer: {{prompt:Customer}}',
      '- Segment: {{select:Segment|Individual,SMB,Mid-market,Enterprise,Internal}}',
      '- Owner: {{prompt:Owner}}',
      '- Health: {{select:Health|Green,Yellow,Red,Unknown}}',
      '',
      '## People',
      '- Name:  Role:  Notes: ',
      '',
      '## Goals',
      '- ',
      '',
      '## Use Cases',
      '- Workflow:',
      '- Success criteria:',
      '',
      '## Environment',
      '- Tools:',
      '- Integrations:',
      '- Constraints:',
      '',
      '## Timeline',
      '- {{date}} - Profile created',
      '',
      '## Pain Points',
      '- ',
      '',
      '## Success Signals',
      '- ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Opportunities',
      '- ',
      '',
      '## Related Notes',
      '- [[ ]]',
      '',
      '## Agent Tasks',
      '- [ ] Summarize recent notes about this customer',
      '- [ ] Extract open follow-ups and owners',
      '- [ ] Identify missing context before the next meeting'
    ].join('\n')
  },
  contentCalendar: {
    file: 'Content Calendar.md',
    content: [
      '---',
      'type: content-calendar',
      'status: {{select:Status|Planning,Active,Paused,Archived}}',
      'channel: {{select:Channel|Blog,Newsletter,Social,Docs,Video,Multi-channel}}',
      'owner: {{prompt:Owner}}',
      'month: {{prompt:Month}}',
      'created: {{date}}',
      'tags: [content, calendar]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Themes',
      '- Theme:  Notes: ',
      '',
      '## Calendar',
      '| Date | Channel | Asset | Status | Owner | Link |',
      '| --- | --- | --- | --- | --- | --- |',
      '|  |  |  |  |  |  |',
      '',
      '## Production Plan',
      '### Not Started',
      '- ',
      '',
      '### Drafting',
      '- ',
      '',
      '### Review',
      '- ',
      '',
      '### Scheduled',
      '- ',
      '',
      '### Published',
      '- ',
      '',
      '## Distribution',
      '- Primary channel:',
      '- Repurposing plan:',
      '- CTA:',
      '',
      '## Dependencies',
      '- Source material:',
      '- Design:',
      '- Reviewers:',
      '',
      '## Agent Tasks',
      '- [ ] Turn approved ideas into draft briefs',
      '- [ ] Find stale or blocked calendar items',
      '- [ ] Summarize upcoming publishing workload'
    ].join('\n')
  },
  learningPlan: {
    file: 'Learning Plan.md',
    content: [
      '---',
      'type: learning-plan',
      'status: {{select:Status|Not started,Active,Paused,Complete}}',
      'topic: {{prompt:Topic}}',
      'target_date: {{prompt:Target date}}',
      'created: {{date}}',
      'tags: [learning, plan]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Outcome',
      '{{prompt:Outcome}}',
      '',
      '## Current Level',
      '{{select:Current level|Beginner,Working knowledge,Intermediate,Advanced}}',
      '',
      '## Curriculum',
      '- Module:  Goal:  Evidence: ',
      '',
      '## Resources',
      '- Resource:  Type:  Link:  Priority: ',
      '',
      '## Practice Projects',
      '- Project:  Skill tested:  Done when: ',
      '',
      '## Schedule',
      '- Week:  Focus:  Output: ',
      '',
      '## Notes',
      '- ',
      '',
      '## Assessment',
      '- Can explain:',
      '- Can build:',
      '- Needs more practice:',
      '',
      '## Agent Coach Tasks',
      '- [ ] Convert resources into a weekly plan',
      '- [ ] Quiz weak areas from notes in this topic',
      '- [ ] Suggest practice tasks based on gaps'
    ].join('\n')
  },
  decisionReview: {
    file: 'Decision Review.md',
    content: [
      '---',
      'type: decision-review',
      'status: {{select:Status|Scheduled,Reviewing,Done}}',
      'decision_date: {{prompt:Decision date}}',
      'review_date: {{date}}',
      'owner: {{prompt:Owner}}',
      'tags: [decision, review]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Original Decision',
      '- Link: [[ ]]',
      '- Summary: {{prompt:Original decision}}',
      '- Intended outcome:',
      '',
      '## Actual Outcome',
      '- What happened:',
      '- What did not happen:',
      '- Who was affected:',
      '',
      '## Evidence',
      '- Metric or signal:  Result:  Source: ',
      '',
      '## What Changed',
      '- Assumption:',
      '- New information:',
      '- Constraint:',
      '',
      '## Consequences',
      '- Positive:',
      '- Negative:',
      '- Unexpected:',
      '',
      '## Review Decision',
      '{{select:Review decision|Keep,Change,Reverse,Defer}}',
      '',
      '## Follow-up Decisions',
      '- [ ] Decision needed:  Owner:  Due: ',
      '',
      '## Agent Tasks',
      '- [ ] Compare this review with the original decision note',
      '- [ ] Pull supporting evidence from linked notes',
      '- [ ] Draft follow-up decision records if needed'
    ].join('\n')
  },
  releaseNotes: {
    file: 'Release Notes.md',
    content: [
      '---',
      'type: release-notes',
      'version: {{prompt:Version}}',
      'date: {{date}}',
      'tags: [release]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Highlights',
      '- ',
      '',
      '## Added',
      '- ',
      '',
      '## Improved',
      '- ',
      '',
      '## Fixed',
      '- ',
      '',
      '## Notes',
      ''
    ].join('\n')
  },
  changelog: {
    file: 'Changelog Entry.md',
    content: [
      '---',
      'type: changelog',
      'date: {{datetime}}',
      'change_type: {{select:Change type|Feature,Improvement,Fix,Docs,Internal}}',
      'tags: [forge, changelog]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Date',
      '{{datetime}}',
      '',
      '## Type',
      '{{select:Change type|Feature,Improvement,Fix,Docs,Internal}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## User Impact',
      '{{prompt:User impact}}',
      '',
      '## Website Copy Notes',
      '{{prompt:Website copy notes}}',
      '',
      '## Validation',
      '',
      '## Implementation Notes',
      ''
    ].join('\n')
  },
  publishPage: {
    file: 'Publish Page.md',
    content: [
      '---',
      'type: publish-page',
      'status: {{select:Status|Draft,Review,Published}}',
      'slug: {{prompt:Slug}}',
      'description: {{prompt:Description}}',
      'created: {{date}}',
      'tags: [publish]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Body',
      '',
      '## Calls to Action',
      '- ',
      '',
      '## Assets',
      '- ',
      '',
      '## Links',
      '- ',
      '',
      '## Publishing Checklist',
      '- [ ] Check links',
      '- [ ] Check images and media',
      '- [ ] Check title and description',
      '- [ ] Export static site',
      ''
    ].join('\n')
  },
  publishRunbook: {
    file: 'Publish Runbook.md',
    content: [
      '---',
      'type: publish-runbook',
      'status: {{select:Status|Draft,Ready,Running,Complete,Blocked}}',
      'target: {{prompt:Publish target}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [publish, runbook]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Inputs',
      '- Vault: {{vault}}',
      '- Publish target: {{prompt:Publish target}}',
      '- Output directory:',
      '- Source folders:',
      '- Owner: {{prompt:Owner}}',
      '',
      '## Preflight',
      '- [ ] Vault health report reviewed',
      '- [ ] Broken links triaged',
      '- [ ] Draft pages marked ready',
      '- [ ] Assets checked',
      '- [ ] Changelog or release notes prepared',
      '',
      '## Run Steps',
      '```bash',
      'forge --vault "{{vault}}" analyze --json',
      'forge --vault "{{vault}}" publish --out "{{prompt:Publish target}}" --clean --json',
      '```',
      '',
      '## QA',
      '- [ ] Homepage loads',
      '- [ ] Navigation works',
      '- [ ] Tags or indexes render',
      '- [ ] Images and attachments load',
      '- [ ] Search or external checks pass',
      '',
      '## Rollback',
      '- Previous output:',
      '- Restore command:',
      '- Owner to notify:',
      '',
      '## Publish Log',
      '- {{datetime}} - Result:  Notes:',
      '',
      '## Agent Tasks',
      '- [ ] Summarize analyze output before publishing',
      '- [ ] Capture publish totals and broken-link count',
      '- [ ] Draft user-facing release notes from changed pages'
    ].join('\n')
  },
  transcriptCleanup: {
    file: 'Transcript Cleanup.md',
    content: [
      '---',
      'type: transcript-cleanup',
      'status: {{select:Status|Raw,Cleaning,Reviewed,Published}}',
      'source: {{prompt:Source recording or note}}',
      'created: {{date}}',
      'tags: [transcript, voice]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Cleanup Instructions',
      '{{prompt:Cleanup instructions}}',
      '',
      '## Speaker Notes',
      '{{prompt:Speaker names}}',
      '',
      '## Raw Transcript',
      '',
      '## Cleaned Transcript',
      '',
      '## Summary',
      '- ',
      '',
      '## Key Points',
      '- ',
      '',
      '## Action Items',
      '- [ ] ',
      '',
      '## Quotes to Preserve',
      '- ',
      '',
      '## Follow-up Questions',
      '- ',
      '',
      '## Agent Instructions',
      '- Preserve speaker intent.',
      '- Remove filler and obvious transcription mistakes.',
      '- Keep uncertain phrases marked with [?].',
      '- Do not invent facts that are not in the transcript.'
    ].join('\n')
  }
}
