import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const builtInTemplateVariables = ['title', 'date', 'time', 'datetime', 'vault', 'template', 'folder']
const builtInVariableSet = new Set(builtInTemplateVariables)
const lines = (...items) => items.join('\n')

export const BUILT_IN_STARTER_TEMPLATES = [
  {
    kind: 'daily',
    label: 'Daily note',
    detail: 'Focus, log, decisions, follow-ups',
    file: 'Daily.md',
    content: lines(
      '---',
      'date: {{date}}',
      'tags: [daily]',
      '---',
      '',
      '# {{date}}',
      '',
      '## Focus',
      '{{prompt:Focus}}',
      '',
      '## Priorities',
      '- [ ] ',
      '- [ ] ',
      '- [ ] ',
      '',
      '## Schedule',
      '- ',
      '',
      '## Notes',
      '',
      '## Decisions',
      '- ',
      '',
      '## Tasks',
      '- [ ] ',
      '',
      '## Follow-ups',
      '- '
    )
  },
  {
    kind: 'weeklyReview',
    label: 'Weekly review',
    detail: 'Wins, learnings, open loops, next week',
    file: 'Weekly Review.md',
    content: lines(
      '---',
      'type: weekly-review',
      'week: {{prompt:Week}}',
      'status: {{select:Status|Draft,Reviewed,Archived}}',
      'created: {{date}}',
      'tags: [weekly-review, review]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Week',
      '{{prompt:Week}}',
      '',
      '## Wins',
      '- ',
      '',
      '## Shipped',
      '- ',
      '',
      '## Learned',
      '- ',
      '',
      '## Metrics',
      '- Metric:  Result:  Notes: ',
      '',
      '## Open Loops',
      '- [ ] ',
      '',
      '## Decisions',
      '- ',
      '',
      '## Next Week',
      '- Focus:',
      '- Risks:',
      '- First action:',
      '',
      '## Agent Follow-up',
      '- Notes to summarize:',
      '- Links to repair:',
      '- Tasks to extract:'
    )
  },
  {
    kind: 'meeting',
    label: 'Meeting notes',
    detail: 'Agenda, decisions, action items',
    file: 'Meeting Notes.md',
    content: lines(
      '---',
      'type: meeting',
      'date: {{date}}',
      'status: {{select:Status|Scheduled,In progress,Done}}',
      'tags: [meeting]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Attendees',
      '{{prompt:Attendees}}',
      '',
      '## Agenda',
      '{{prompt:Agenda}}',
      '',
      '## Notes',
      '',
      '## Decisions',
      '- ',
      '',
      '## Action Items',
      '- [ ] Owner:  Due:  Task: ',
      '',
      '## Follow-ups',
      '- '
    )
  },
  {
    kind: 'sourceNote',
    label: 'Source note',
    detail: 'Literature notes and source extraction',
    file: 'Source Note.md',
    content: lines(
      '---',
      'type: source-note',
      'source_type: {{select:Source type|Book,Article,Paper,Podcast,Video,Docs,Other}}',
      'status: {{select:Status|Queued,Reading,Processed,Archived}}',
      'author: {{prompt:Author}}',
      'source: {{prompt:Source}}',
      'url: {{prompt:URL}}',
      'created: {{date}}',
      'tags: [source, literature]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Citation',
      '- Author: {{prompt:Author}}',
      '- Source: {{prompt:Source}}',
      '- URL: {{prompt:URL}}',
      '',
      '## Why This Matters',
      '{{prompt:Why this matters}}',
      '',
      '## Summary',
      '',
      '## Key Ideas',
      '- Idea:  Evidence:  Confidence: ',
      '',
      '## Quotes',
      '- ',
      '',
      '## Connections',
      '- Related notes: ',
      '- Contradicts: ',
      '- Supports: ',
      '',
      '## Questions',
      '- ',
      '',
      '## Agent Extraction Tasks',
      '- [ ] Pull durable claims into evergreen notes',
      '- [ ] Link people, organizations, and concepts',
      '- [ ] Flag uncertain or unsupported claims'
    )
  },
  {
    kind: 'knowledgeMap',
    label: 'Knowledge map',
    detail: 'MOC hub for linked notes and gaps',
    file: 'Knowledge Map.md',
    content: lines(
      '---',
      'type: knowledge-map',
      'topic: {{prompt:Topic}}',
      'status: {{select:Status|Draft,Living,Archived}}',
      'created: {{date}}',
      'tags: [moc, map]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Purpose',
      '{{prompt:Purpose}}',
      '',
      '## Core Notes',
      '- [[ ]]',
      '',
      '## Clusters',
      '### People',
      '- ',
      '',
      '### Concepts',
      '- ',
      '',
      '### Projects',
      '- ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Gaps',
      '- Missing note:',
      '- Stale note:',
      '- Broken link:',
      '',
      '## Next Links to Create',
      '- [[ ]]',
      '',
      '## Agent Maintenance',
      '- [ ] Find unlinked mentions for this topic',
      '- [ ] Suggest notes that belong in this map',
      '- [ ] Summarize changes since last review'
    )
  },
  {
    kind: 'calloutLibrary',
    label: 'Callout library / snippets',
    detail: 'Reusable note, tip, warning, question, and quote snippets',
    file: 'Callout Library.md',
    content: lines(
      '---',
      'type: callout-library',
      'status: {{select:Status|Draft,Active,Archived}}',
      'created: {{date}}',
      'tags: [callouts, templates]',
      '---',
      '',
      '# {{title}}',
      '',
      '## How to Use',
      '- Copy a snippet into any note.',
      '- Replace placeholder text with the actual context.',
      '- Keep callouts short enough to scan.',
      '',
      '## Note',
      '> [!note] Context',
      '> Use this for neutral background, definitions, or source notes.',
      '',
      '## Tip',
      '> [!tip] Better Path',
      '> Use this for a recommended action, shortcut, or pattern.',
      '',
      '## Warning',
      '> [!warning] Check Before Shipping',
      '> Use this for risks, blockers, caveats, or destructive steps.',
      '',
      '## Question',
      '> [!question] Open Question',
      '> Use this for unresolved decisions, research prompts, or agent follow-up.',
      '',
      '## Quote',
      '> [!quote] Source Quote',
      '> Use this for copied source text that needs attribution.',
      '> Source: {{prompt:Source}}',
      '',
      '## Agent Notes',
      '- Preserve callout type and title when rewriting notes.',
      '- Do not convert warnings into neutral notes.',
      '- Keep quoted text attributed to its source.'
    )
  },
  {
    kind: 'agentTask',
    label: 'Agent task',
    detail: 'Precise AI work briefs',
    file: 'Agent Task Brief.md',
    content: lines(
      '---',
      'type: agent-task',
      'status: {{select:Status|Ready,In progress,Blocked,Done}}',
      'created: {{date}}',
      'tags: [agent, task]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Context',
      '- Vault: {{vault}}',
      '- Folder: {{folder}}',
      '- Related notes: {{prompt:Related notes}}',
      '',
      '## Constraints',
      '- Preserve existing user changes.',
      '- Keep paths relative to the vault.',
      '- Stay within the requested ownership boundary.',
      '- Prefer small, reviewable edits.',
      '',
      '## Inputs',
      '- Files or folders: {{prompt:Files or folders}}',
      '- External references: {{prompt:External references}}',
      '',
      '## Definition of Done',
      '- [ ] Requested change is complete',
      '- [ ] Targeted validation has run or is explained',
      '- [ ] Files changed are summarized',
      '',
      '## Checklist',
      '- [ ] Inspect current state',
      '- [ ] Implement the requested change',
      '- [ ] Verify behavior',
      '- [ ] Summarize outcome',
      '',
      '## Verification',
      '',
      '## Result',
      ''
    )
  },
  {
    kind: 'agentReview',
    label: 'Agent review / QA',
    detail: 'Checklist for reviewing agent work',
    file: 'Agent Review QA.md',
    content: lines(
      '---',
      'type: agent-review',
      'status: {{select:Status|Ready,Reviewing,Changes requested,Approved,Blocked}}',
      'reviewer: {{prompt:Reviewer}}',
      'created: {{date}}',
      'tags: [agent, review, qa]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Scope',
      '- Request: {{prompt:Request}}',
      '- Files or notes reviewed: {{prompt:Files or notes reviewed}}',
      '- Ownership boundary:',
      '- Out of scope:',
      '',
      '## Review Checklist',
      '- [ ] Requested behavior is implemented',
      '- [ ] Unrelated edits are not included',
      '- [ ] Markdown renders cleanly',
      '- [ ] Links, tags, and frontmatter are valid',
      '- [ ] Agent-facing instructions are clear',
      '- [ ] Validation output is captured or explained',
      '',
      '## Findings',
      '- Severity:',
      '- Location:',
      '- Issue:',
      '- Recommendation:',
      '',
      '## Callouts to Add',
      '> [!warning] Risk',
      '> Note any risky follow-up or unresolved blocker.',
      '',
      '> [!question] Open Question',
      '> Note anything that needs user or owner input.',
      '',
      '## QA Notes',
      '',
      '## Decision',
      '{{select:Decision|Approve,Request changes,Block,Needs owner review}}',
      '',
      '## Follow-up Tasks',
      '- [ ] '
    )
  },
  {
    kind: 'seoBrief',
    label: 'SEO/content brief',
    detail: 'Audience, intent, outline, links',
    file: 'SEO Content Brief.md',
    content: lines(
      '---',
      'type: seo-brief',
      'status: {{select:Status|Brief,Drafting,Review,Published}}',
      'content_type: {{select:Content type|Article,Landing page,Docs,Case study,Email}}',
      'created: {{date}}',
      'tags: [seo, content]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Search Target',
      '- Primary keyword: {{prompt:Primary keyword}}',
      '- Secondary keywords: {{prompt:Secondary keywords}}',
      '- Search intent: {{select:Search intent|Informational,Commercial,Transactional,Navigational}}',
      '',
      '## Angle',
      '{{prompt:Angle}}',
      '',
      '## Reader Promise',
      '',
      '## Outline',
      '- H1: {{title}}',
      '- H2:',
      '- H2:',
      '- H2:',
      '',
      '## Evidence and Sources',
      '- ',
      '',
      '## Internal Links',
      '- ',
      '',
      '## Meta',
      '- Title tag:',
      '- Description:',
      '- Slug:',
      '',
      '## Notes for Agent',
      '- Preserve factual uncertainty.',
      '- Suggest sources before drafting claims.',
      '- Keep headings scannable.',
      ''
    )
  },
  {
    kind: 'research',
    label: 'Research brief',
    detail: 'Questions, sources, synthesis',
    file: 'Research Brief.md',
    content: lines(
      '---',
      'type: research-brief',
      'status: {{select:Status|Scoping,Researching,Synthesizing,Done}}',
      'created: {{date}}',
      'tags: [research]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Research Question',
      '{{prompt:Research question}}',
      '',
      '## Decision or Use',
      '{{prompt:Decision or use}}',
      '',
      '## Source List',
      '- Source:  Why it matters: ',
      '',
      '## Findings',
      '- Finding:  Evidence:  Confidence: ',
      '',
      '## Synthesis',
      '',
      '## Risks and Gaps',
      '- ',
      '',
      '## Recommended Next Step',
      ''
    )
  },
  {
    kind: 'sprintPlan',
    label: 'Sprint plan',
    detail: 'Goals, scope, capacity, risks',
    file: 'Sprint Plan.md',
    content: lines(
      '---',
      'type: sprint-plan',
      'sprint: {{prompt:Sprint}}',
      'status: {{select:Status|Planned,Active,Complete,Closed}}',
      'start: {{prompt:Start date}}',
      'end: {{prompt:End date}}',
      'created: {{date}}',
      'tags: [sprint, planning]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Sprint Goal',
      '{{prompt:Sprint goal}}',
      '',
      '## Capacity',
      '- People:',
      '- Focus days:',
      '- Known interruptions:',
      '',
      '## Commitments',
      '- [ ] Owner:  Work:  Done when: ',
      '',
      '## Backlog Candidates',
      '- ',
      '',
      '## Execution Board',
      '### Now',
      '- ',
      '',
      '### Next',
      '- ',
      '',
      '### Blocked',
      '- ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Review Criteria',
      '- Demo:',
      '- Metrics:',
      '- Retro notes:',
      '',
      '## Agent Tasks',
      '- [ ] Break commitments into implementation tasks',
      '- [ ] Check linked specs and issues for stale assumptions',
      '- [ ] Draft end-of-sprint summary'
    )
  },
  {
    kind: 'productSpec',
    label: 'PRD',
    detail: 'Requirements and launch criteria',
    file: 'PRD.md',
    content: lines(
      '---',
      'type: prd',
      'status: {{select:Status|Draft,Review,Ready,Building,Shipped}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [product, prd]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Problem',
      '{{prompt:Problem}}',
      '',
      '## Users',
      '{{prompt:Users}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Non-goals',
      '- ',
      '',
      '## Requirements',
      '- Must:',
      '- Should:',
      '- Could:',
      '',
      '## User Experience',
      '- Entry point:',
      '- Primary flow:',
      '- Empty/error states:',
      '',
      '## Data and Instrumentation',
      '- Events:',
      '- Success metrics:',
      '- Guardrails:',
      '',
      '## Rollout Plan',
      '- ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Launch Checklist',
      '- [ ] Product review',
      '- [ ] Engineering review',
      '- [ ] Support/docs ready',
      ''
    )
  },
  {
    kind: 'project',
    label: 'Project plan',
    detail: 'Scope, milestones, risks',
    file: 'Project Plan.md',
    content: lines(
      '---',
      'type: project-plan',
      'status: {{select:Status|Planning,Active,Paused,Done}}',
      'owner: {{prompt:Owner}}',
      'target: {{prompt:Target date}}',
      'tags: [project]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goal',
      '{{prompt:Goal}}',
      '',
      '## Background',
      '',
      '## Scope',
      '### In scope',
      '- ',
      '',
      '### Out of scope',
      '- ',
      '',
      '## Deliverables',
      '- ',
      '',
      '## Milestones',
      '- [ ] Milestone:  Owner:  Date: ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Next Actions',
      '- [ ] '
    )
  },
  {
    kind: 'supportTicket',
    label: 'Support ticket',
    detail: 'Customer issue tracking and resolution',
    file: 'Support Ticket.md',
    content: lines(
      '---',
      'type: support-ticket',
      'status: {{select:Status|New,Waiting on customer,Investigating,Resolved,Closed}}',
      'priority: {{select:Priority|Low,Normal,High,Urgent}}',
      'customer: {{prompt:Customer}}',
      'created: {{date}}',
      'tags: [support]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Customer Context',
      '- Customer: {{prompt:Customer}}',
      '- Plan/account:',
      '- Related notes:',
      '',
      '## Timeline',
      '- {{datetime}} - Created',
      '',
      '## Reproduction',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Expected',
      '',
      '## Actual',
      '',
      '## Workaround',
      '',
      '## Resolution',
      '',
      '## Follow-up',
      '- [ ] Reply to customer',
      '- [ ] Update docs or saved reply',
      '- [ ] Link related bug or decision'
    )
  },
  {
    kind: 'experimentLog',
    label: 'Experiment log',
    detail: 'Hypothesis, procedure, results',
    file: 'Experiment Log.md',
    content: lines(
      '---',
      'type: experiment-log',
      'status: {{select:Status|Proposed,Running,Analyzing,Concluded}}',
      'owner: {{prompt:Owner}}',
      'started: {{date}}',
      'tags: [experiment]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Hypothesis',
      '{{prompt:Hypothesis}}',
      '',
      '## Success Criteria',
      '- ',
      '',
      '## Variables',
      '- Independent:',
      '- Dependent:',
      '- Controls:',
      '',
      '## Setup',
      '',
      '## Procedure',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Observations',
      '- ',
      '',
      '## Data',
      '- Source:',
      '- Result:',
      '',
      '## Conclusion',
      '',
      '## Decision',
      '{{select:Decision|Keep,Iterate,Stop,Inconclusive}}',
      '',
      '## Follow-up',
      '- [ ] '
    )
  },
  {
    kind: 'contentOutline',
    label: 'Content outline',
    detail: 'Structured drafting brief',
    file: 'Content Outline.md',
    content: lines(
      '---',
      'type: content-outline',
      'status: {{select:Status|Outline,Drafting,Review,Published}}',
      'format: {{select:Format|Article,Guide,Newsletter,Video,Talk,Thread}}',
      'audience: {{prompt:Audience}}',
      'created: {{date}}',
      'tags: [content, outline]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goal',
      '{{prompt:Goal}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Reader Promise',
      '',
      '## Angle',
      '{{prompt:Angle}}',
      '',
      '## Outline',
      '- H1: {{title}}',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '- H2:',
      '  - Point:',
      '  - Evidence:',
      '',
      '## Evidence and Links',
      '- ',
      '',
      '## Distribution Notes',
      '- Channel:',
      '- CTA:',
      '',
      '## Agent Drafting Notes',
      '- Preserve claims that need citations.',
      '- Keep examples concrete.',
      '- Do not fill gaps with invented facts.'
    )
  },
  {
    kind: 'interviewNotes',
    label: 'Interview notes',
    detail: 'Research, customer, or hiring notes',
    file: 'Interview Notes.md',
    content: lines(
      '---',
      'type: interview-notes',
      'interview_type: {{select:Interview type|User research,Candidate,Customer,Expert,Internal}}',
      'participant: {{prompt:Participant}}',
      'date: {{date}}',
      'status: {{select:Status|Scheduled,Completed,Synthesized,Archived}}',
      'tags: [interview]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Participant Context',
      '- Name: {{prompt:Participant}}',
      '- Role/context:',
      '- Related notes:',
      '',
      '## Questions',
      '- ',
      '',
      '## Notes',
      '',
      '## Highlights',
      '- ',
      '',
      '## Pain Points',
      '- ',
      '',
      '## Quotes',
      '- ',
      '',
      '## Opportunities',
      '- ',
      '',
      '## Follow-ups',
      '- [ ] ',
      '',
      '## Agent Synthesis Instructions',
      '- Separate observation from interpretation.',
      '- Preserve exact quotes only when recorded.',
      '- Link themes back to source notes.'
    )
  },
  {
    kind: 'bugReport',
    label: 'Bug report',
    detail: 'Repro, impact, fix notes',
    file: 'Bug Report.md',
    content: lines(
      '---',
      'type: bug',
      'status: {{select:Status|New,Triaged,Fixing,Fixed,Won\'t fix}}',
      'severity: {{select:Severity|Low,Medium,High,Critical}}',
      'created: {{date}}',
      'tags: [bug]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Impact',
      '{{prompt:Impact}}',
      '',
      '## Environment',
      '{{prompt:Environment}}',
      '',
      '## Steps to Reproduce',
      '1. ',
      '2. ',
      '3. ',
      '',
      '## Expected',
      '',
      '## Actual',
      '',
      '## Suspected Cause',
      '',
      '## Workaround',
      '',
      '## Notes / Fix',
      ''
    )
  },
  {
    kind: 'decision',
    label: 'Decision record',
    detail: 'Options, rationale, consequences',
    file: 'Decision Record.md',
    content: lines(
      '---',
      'type: decision-record',
      'status: {{select:Status|Proposed,Accepted,Rejected,Superseded}}',
      'date: {{date}}',
      'tags: [decision]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Decision',
      '{{prompt:Decision}}',
      '',
      '## Context',
      '',
      '## Options',
      '- Option A:',
      '- Option B:',
      '',
      '## Rationale',
      '',
      '## Consequences',
      '- ',
      '',
      '## Review Date',
      '{{prompt:Review date}}',
      ''
    )
  },
  {
    kind: 'incidentPostmortem',
    label: 'Incident postmortem',
    detail: 'Impact, timeline, causes, follow-up',
    file: 'Incident Postmortem.md',
    content: lines(
      '---',
      'type: incident-postmortem',
      'status: {{select:Status|Draft,Reviewed,Closed}}',
      'severity: {{select:Severity|SEV1,SEV2,SEV3,SEV4}}',
      'incident_date: {{prompt:Incident date}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [incident, postmortem]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Impact',
      '- Users affected:',
      '- Duration:',
      '- Systems:',
      '- Customer impact:',
      '',
      '## Timeline',
      '- {{datetime}} - Detected',
      '-  - Mitigated',
      '-  - Resolved',
      '',
      '## Detection',
      '- Signal:',
      '- Alert or report:',
      '- Time to detect:',
      '',
      '## Root Cause',
      '- Trigger:',
      '- Contributing factors:',
      '- What changed:',
      '',
      '## Resolution',
      '- Mitigation:',
      '- Permanent fix:',
      '- Verification:',
      '',
      '## What Went Well',
      '- ',
      '',
      '## What Went Wrong',
      '- ',
      '',
      '## Follow-up Actions',
      '- [ ] Owner:  Due:  Action: ',
      '',
      '## Agent Tasks',
      '- [ ] Extract action items with owners and due dates',
      '- [ ] Link related support tickets, bugs, and decisions',
      '- [ ] Draft customer-facing summary if needed'
    )
  },
  {
    kind: 'technicalRFC',
    label: 'Technical RFC',
    detail: 'Proposal, tradeoffs, rollout plan',
    file: 'Technical RFC.md',
    content: lines(
      '---',
      'type: technical-rfc',
      'status: {{select:Status|Draft,In review,Accepted,Rejected,Implemented}}',
      'owner: {{prompt:Owner}}',
      'reviewers: {{prompt:Reviewers}}',
      'created: {{date}}',
      'tags: [rfc, engineering]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Problem',
      '{{prompt:Problem}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Non-goals',
      '- ',
      '',
      '## Proposed Design',
      '- Architecture:',
      '- Data model:',
      '- User or developer flow:',
      '',
      '## Alternatives Considered',
      '- Option:  Pros:  Cons: ',
      '',
      '## Tradeoffs',
      '- Benefit:',
      '- Cost:',
      '- Risk:',
      '',
      '## Rollout Plan',
      '- Phase:',
      '- Migration:',
      '- Rollback:',
      '',
      '## Observability',
      '- Metrics:',
      '- Logs:',
      '- Alerts:',
      '',
      '## Open Questions',
      '- ',
      '',
      '## Decision Log',
      '- {{date}} - ',
      '',
      '## Agent Review Notes',
      '- [ ] Check assumptions against linked specs or code',
      '- [ ] Identify missing edge cases and migration risks',
      '- [ ] Summarize unresolved reviewer questions'
    )
  },
  {
    kind: 'apiSpec',
    label: 'API spec',
    detail: 'Endpoint contract and examples',
    file: 'API Spec.md',
    content: lines(
      '---',
      'type: api-spec',
      'status: {{select:Status|Draft,Review,Stable,Deprecated}}',
      'method: {{select:Method|GET,POST,PUT,PATCH,DELETE}}',
      'endpoint: {{prompt:Endpoint}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [api, spec]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Overview',
      '{{prompt:Overview}}',
      '',
      '## Endpoint',
      '- Method: {{select:Method|GET,POST,PUT,PATCH,DELETE}}',
      '- Path: {{prompt:Endpoint}}',
      '- Auth: {{select:Auth|None,API key,OAuth,Session,Service token}}',
      '',
      '## Request Parameters',
      '| Name | Type | Required | Description |',
      '| --- | --- | --- | --- |',
      '|  |  |  |  |',
      '',
      '## Request Body',
      '```json',
      '{}',
      '```',
      '',
      '## Response',
      '```json',
      '{}',
      '```',
      '',
      '## Error Cases',
      '| Status | Code | Condition | Recovery |',
      '| --- | --- | --- | --- |',
      '|  |  |  |  |',
      '',
      '## Examples',
      '```bash',
      'curl ',
      '```',
      '',
      '## Compatibility',
      '- Versioning:',
      '- Breaking changes:',
      '- Deprecation plan:',
      '',
      '## Test Cases',
      '- [ ] Happy path',
      '- [ ] Auth failure',
      '- [ ] Validation failure',
      '- [ ] Rate limit or quota behavior',
      '',
      '## Agent Tasks',
      '- [ ] Generate example requests and responses',
      '- [ ] Compare implementation behavior with this contract',
      '- [ ] Flag undocumented fields or status codes'
    )
  },
  {
    kind: 'launchPlan',
    label: 'Launch plan',
    detail: 'Readiness, rollout, comms, metrics',
    file: 'Launch Plan.md',
    content: lines(
      '---',
      'type: launch-plan',
      'status: {{select:Status|Planning,Ready,Launching,Launched,Paused}}',
      'owner: {{prompt:Owner}}',
      'launch_date: {{prompt:Launch date}}',
      'audience: {{prompt:Audience}}',
      'created: {{date}}',
      'tags: [launch, go-to-market]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Objective',
      '{{prompt:Objective}}',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Scope',
      '### Included',
      '- ',
      '',
      '### Excluded',
      '- ',
      '',
      '## Launch Criteria',
      '- Product:',
      '- Docs:',
      '- Support:',
      '- Analytics:',
      '',
      '## Rollout Plan',
      '- Phase:  Audience:  Date:  Owner: ',
      '',
      '## Communications',
      '- Internal:',
      '- Customer:',
      '- Website or docs:',
      '- Social or community:',
      '',
      '## Support Readiness',
      '- Saved replies:',
      '- Known issues:',
      '- Escalation path:',
      '',
      '## Metrics',
      '- Success metric:',
      '- Guardrail metric:',
      '- Review date:',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Checklist',
      '- [ ] Launch owner assigned',
      '- [ ] Rollback or pause plan written',
      '- [ ] Docs and support notes reviewed',
      '- [ ] Metrics dashboard or query ready',
      '',
      '## Agent Tasks',
      '- [ ] Draft announcement copy from scope and audience',
      '- [ ] Check linked PRD, RFC, and support notes for gaps',
      '- [ ] Summarize launch readiness blockers'
    )
  },
  {
    kind: 'customerProfile',
    label: 'Customer profile',
    detail: 'Account context, goals, risks, next steps',
    file: 'Customer Profile.md',
    content: lines(
      '---',
      'type: customer-profile',
      'status: {{select:Status|Prospect,Active,At risk,Churned,Archived}}',
      'customer: {{prompt:Customer}}',
      'segment: {{select:Segment|Individual,SMB,Mid-market,Enterprise,Internal}}',
      'owner: {{prompt:Owner}}',
      'created: {{date}}',
      'tags: [customer, profile]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Snapshot',
      '- Customer: {{prompt:Customer}}',
      '- Segment: {{select:Segment|Individual,SMB,Mid-market,Enterprise,Internal}}',
      '- Owner: {{prompt:Owner}}',
      '- Health: {{select:Health|Green,Yellow,Red,Unknown}}',
      '',
      '## People',
      '- Name:  Role:  Notes: ',
      '',
      '## Goals',
      '- ',
      '',
      '## Use Cases',
      '- Workflow:',
      '- Success criteria:',
      '',
      '## Environment',
      '- Tools:',
      '- Integrations:',
      '- Constraints:',
      '',
      '## Timeline',
      '- {{date}} - Profile created',
      '',
      '## Pain Points',
      '- ',
      '',
      '## Success Signals',
      '- ',
      '',
      '## Risks',
      '- Risk:  Mitigation: ',
      '',
      '## Opportunities',
      '- ',
      '',
      '## Related Notes',
      '- [[ ]]',
      '',
      '## Agent Tasks',
      '- [ ] Summarize recent notes about this customer',
      '- [ ] Extract open follow-ups and owners',
      '- [ ] Identify missing context before the next meeting'
    )
  },
  {
    kind: 'contentCalendar',
    label: 'Content calendar',
    detail: 'Campaign schedule and publishing workflow',
    file: 'Content Calendar.md',
    content: lines(
      '---',
      'type: content-calendar',
      'status: {{select:Status|Planning,Active,Paused,Archived}}',
      'channel: {{select:Channel|Blog,Newsletter,Social,Docs,Video,Multi-channel}}',
      'owner: {{prompt:Owner}}',
      'month: {{prompt:Month}}',
      'created: {{date}}',
      'tags: [content, calendar]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Goals',
      '- ',
      '',
      '## Audience',
      '{{prompt:Audience}}',
      '',
      '## Themes',
      '- Theme:  Notes: ',
      '',
      '## Calendar',
      '| Date | Channel | Asset | Status | Owner | Link |',
      '| --- | --- | --- | --- | --- | --- |',
      '|  |  |  |  |  |  |',
      '',
      '## Production Board',
      '### Not Started',
      '- ',
      '',
      '### Drafting',
      '- ',
      '',
      '### Review',
      '- ',
      '',
      '### Scheduled',
      '- ',
      '',
      '### Published',
      '- ',
      '',
      '## Distribution',
      '- Primary channel:',
      '- Repurposing plan:',
      '- CTA:',
      '',
      '## Dependencies',
      '- Source material:',
      '- Design:',
      '- Reviewers:',
      '',
      '## Agent Tasks',
      '- [ ] Turn approved ideas into draft briefs',
      '- [ ] Find stale or blocked calendar items',
      '- [ ] Summarize upcoming publishing workload'
    )
  },
  {
    kind: 'learningPlan',
    label: 'Learning plan',
    detail: 'Goals, resources, practice, evidence',
    file: 'Learning Plan.md',
    content: lines(
      '---',
      'type: learning-plan',
      'status: {{select:Status|Not started,Active,Paused,Complete}}',
      'topic: {{prompt:Topic}}',
      'target_date: {{prompt:Target date}}',
      'created: {{date}}',
      'tags: [learning, plan]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Outcome',
      '{{prompt:Outcome}}',
      '',
      '## Current Level',
      '{{select:Current level|Beginner,Working knowledge,Intermediate,Advanced}}',
      '',
      '## Curriculum',
      '- Module:  Goal:  Evidence: ',
      '',
      '## Resources',
      '- Resource:  Type:  Link:  Priority: ',
      '',
      '## Practice Projects',
      '- Project:  Skill tested:  Done when: ',
      '',
      '## Schedule',
      '- Week:  Focus:  Output: ',
      '',
      '## Notes',
      '- ',
      '',
      '## Assessment',
      '- Can explain:',
      '- Can build:',
      '- Needs more practice:',
      '',
      '## Agent Coach Tasks',
      '- [ ] Convert resources into a weekly plan',
      '- [ ] Quiz weak areas from notes in this topic',
      '- [ ] Suggest practice tasks based on gaps'
    )
  },
  {
    kind: 'decisionReview',
    label: 'Decision review',
    detail: 'Evaluate outcomes and next decision',
    file: 'Decision Review.md',
    content: lines(
      '---',
      'type: decision-review',
      'status: {{select:Status|Scheduled,Reviewing,Done}}',
      'decision_date: {{prompt:Decision date}}',
      'review_date: {{date}}',
      'owner: {{prompt:Owner}}',
      'tags: [decision, review]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Original Decision',
      '- Link: [[ ]]',
      '- Summary: {{prompt:Original decision}}',
      '- Intended outcome:',
      '',
      '## Actual Outcome',
      '- What happened:',
      '- What did not happen:',
      '- Who was affected:',
      '',
      '## Evidence',
      '- Metric or signal:  Result:  Source: ',
      '',
      '## What Changed',
      '- Assumption:',
      '- New information:',
      '- Constraint:',
      '',
      '## Consequences',
      '- Positive:',
      '- Negative:',
      '- Unexpected:',
      '',
      '## Review Decision',
      '{{select:Review decision|Keep,Change,Reverse,Defer}}',
      '',
      '## Follow-up Decisions',
      '- [ ] Decision needed:  Owner:  Due: ',
      '',
      '## Agent Tasks',
      '- [ ] Compare this review with the original decision note',
      '- [ ] Pull supporting evidence from linked notes',
      '- [ ] Draft follow-up decision records if needed'
    )
  },
  {
    kind: 'publishPage',
    label: 'Publish page',
    detail: 'Public Markdown page draft',
    file: 'Publish Page.md',
    content: lines(
      '---',
      'type: publish-page',
      'status: {{select:Status|Draft,Review,Published}}',
      'slug: {{prompt:Slug}}',
      'description: {{prompt:Description}}',
      'created: {{date}}',
      'tags: [publish]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## Body',
      '',
      '## Calls to Action',
      '- ',
      '',
      '## Assets',
      '- ',
      '',
      '## Links',
      '- ',
      '',
      '## Publishing Checklist',
      '- [ ] Check links',
      '- [ ] Check images and media',
      '- [ ] Check title and description',
      '- [ ] Export static site',
      ''
    )
  },
  {
    kind: 'changelog',
    label: 'Changelog entry',
    detail: 'Forge-style product entries',
    file: 'Changelog Entry.md',
    content: lines(
      '---',
      'type: changelog',
      'date: {{datetime}}',
      'change_type: {{select:Change type|Feature,Improvement,Fix,Docs,Internal}}',
      'tags: [forge, changelog]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Date',
      '{{datetime}}',
      '',
      '## Type',
      '{{select:Change type|Feature,Improvement,Fix,Docs,Internal}}',
      '',
      '## Summary',
      '{{prompt:Summary}}',
      '',
      '## User Impact',
      '{{prompt:User impact}}',
      '',
      '## Website Copy Notes',
      '{{prompt:Website copy notes}}',
      '',
      '## Validation',
      '',
      '## Implementation Notes',
      ''
    )
  },
  {
    kind: 'transcriptCleanup',
    label: 'Transcript cleanup',
    detail: 'Raw transcript to polished notes',
    file: 'Transcript Cleanup.md',
    content: lines(
      '---',
      'type: transcript-cleanup',
      'status: {{select:Status|Raw,Cleaning,Reviewed,Published}}',
      'source: {{prompt:Source recording or note}}',
      'created: {{date}}',
      'tags: [transcript, voice]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Cleanup Instructions',
      '{{prompt:Cleanup instructions}}',
      '',
      '## Speaker Notes',
      '{{prompt:Speaker names}}',
      '',
      '## Raw Transcript',
      '',
      '## Cleaned Transcript',
      '',
      '## Summary',
      '- ',
      '',
      '## Key Points',
      '- ',
      '',
      '## Action Items',
      '- [ ] ',
      '',
      '## Quotes to Preserve',
      '- ',
      '',
      '## Follow-up Questions',
      '- ',
      '',
      '## Agent Instructions',
      '- Preserve speaker intent.',
      '- Remove filler and obvious transcription mistakes.',
      '- Keep uncertain phrases marked with [?].',
      '- Do not invent facts that are not in the transcript.'
    )
  },
  {
    kind: 'releaseNotes',
    label: 'Release notes',
    detail: 'User-facing changes',
    file: 'Release Notes.md',
    content: lines(
      '---',
      'type: release-notes',
      'version: {{prompt:Version}}',
      'date: {{date}}',
      'tags: [release]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Highlights',
      '- ',
      '',
      '## Added',
      '- ',
      '',
      '## Improved',
      '- ',
      '',
      '## Fixed',
      '- ',
      '',
      '## Notes',
      ''
    )
  },
  {
    kind: 'person',
    label: 'Person',
    detail: 'Relationship notes',
    file: 'Person.md',
    content: lines(
      '---',
      'type: person',
      'tags: [person]',
      '---',
      '',
      '# {{title}}',
      '',
      '## Role',
      '{{prompt:Role}}',
      '',
      '## Context',
      '',
      '## Notes',
      '',
      '## Follow-ups',
      ''
    )
  }
]

const declarativeRuntime = {
  kind: 'declarative',
  networkAccess: false,
  arbitraryCode: false,
  allowedHosts: []
}

export const BUILT_IN_EXTENSION_POINTS = [
  {
    id: 'forge.commands',
    kind: 'command',
    label: 'Commands',
    description: 'Contributes local commands that can be surfaced by Forge command UIs.',
    stability: 'experimental',
    owner: 'forge',
    allowedContributionKinds: ['command']
  },
  {
    id: 'forge.markdown.transforms',
    kind: 'markdown-transform',
    label: 'Markdown transforms',
    description: 'Contributes bounded text transforms for selected Markdown content.',
    stability: 'experimental',
    owner: 'forge',
    allowedContributionKinds: ['markdown-transform']
  },
  {
    id: 'forge.note.metadata',
    kind: 'metadata-provider',
    label: 'Note metadata',
    description: 'Contributes local metadata fields derived from vault notes.',
    stability: 'experimental',
    owner: 'forge',
    allowedContributionKinds: ['metadata-provider']
  },
  {
    id: 'forge.sidebar.widgets',
    kind: 'sidebar-widget',
    label: 'Sidebar widgets',
    description: 'Contributes compact local widgets for the Forge sidebars.',
    stability: 'experimental',
    owner: 'forge',
    allowedContributionKinds: ['sidebar-widget']
  },
  {
    id: 'forge.views',
    kind: 'view',
    label: 'Views',
    description: 'Contributes local views backed by vault data already available to Forge.',
    stability: 'experimental',
    owner: 'forge',
    allowedContributionKinds: ['view']
  }
]

export const BUILT_IN_EXTENSION_MANIFESTS = [
  {
    manifestVersion: 1,
    id: 'forge.daily-notes',
    name: 'daily-notes',
    displayName: 'Daily Notes',
    description: "Adds a local command and sidebar entry for opening or creating today's note in the vault.",
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['capture', 'organization'],
    keywords: ['journal', 'daily', 'capture'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.commands', label: 'Commands' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:write',
        reason: 'Creates a Markdown note for the current day when requested.'
      }
    ],
    contributes: [
      {
        id: 'forge.daily-notes.open-today',
        kind: 'command',
        extensionPoint: 'forge.commands',
        label: "Open today's note",
        command: 'forge.dailyNotes.openToday',
        icon: 'CalendarDays'
      },
      {
        id: 'forge.daily-notes.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Today',
        widget: 'daily-note'
      }
    ]
  },
  {
    manifestVersion: 1,
    id: 'forge.reading-stats',
    name: 'reading-stats',
    displayName: 'Reading Stats',
    description: 'Shows local word, character, and estimated reading-time metadata for the active note.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['editing', 'organization'],
    keywords: ['word count', 'metadata', 'stats'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads the active note content already loaded by Forge.'
      }
    ],
    contributes: [
      {
        id: 'forge.reading-stats.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Reading statistics',
        fields: ['wordCount', 'characterCount', 'estimatedReadingMinutes']
      },
      {
        id: 'forge.reading-stats.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Reading stats',
        widget: 'reading-stats'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.markdown-tools',
    name: 'markdown-tools',
    displayName: 'Markdown Tools',
    description: 'Contributes local-only Markdown cleanup and wrapping transforms for selected text.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['editing'],
    keywords: ['markdown', 'format', 'selection'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.commands', label: 'Commands' },
      { id: 'forge.markdown.transforms', label: 'Markdown transforms' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads selected Markdown text and active-note headings before applying local transforms.'
      },
      {
        kind: 'vault:write',
        reason: 'Writes the transformed Markdown back to the current note.'
      }
    ],
    contributes: [
      {
        id: 'forge.markdown-tools.normalize-headings',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Normalize heading spacing',
        transform: 'normalize-headings'
      },
      {
        id: 'forge.markdown-tools.wrap-selection',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Wrap selection',
        transform: 'wrap-selection'
      },
      {
        id: 'forge.markdown-tools.lines-to-checklist',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Convert lines to checklist',
        transform: 'lines-to-checklist'
      },
      {
        id: 'forge.markdown-tools.sort-lines',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Sort selected lines',
        transform: 'sort-lines'
      },
      {
        id: 'forge.markdown-tools.callout',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Wrap selection as callout',
        transform: 'callout'
      },
      {
        id: 'forge.markdown-tools.insert-table-of-contents',
        kind: 'markdown-transform',
        extensionPoint: 'forge.markdown.transforms',
        label: 'Insert generated table of contents',
        transform: 'insert-table-of-contents'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.graph-insights',
    name: 'graph-insights',
    displayName: 'Graph Insights',
    description: 'Adds a local graph summary view for orphans, hubs, backlinks, and broken wikilinks.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['navigation', 'visualization'],
    keywords: ['graph', 'links', 'orphans'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [{ id: 'forge.views', label: 'Views' }],
    permissions: [
      {
        kind: 'vault:metadata',
        reason: 'Uses the local note index and link graph already built by Forge.'
      }
    ],
    contributes: [
      {
        id: 'forge.graph-insights.view',
        kind: 'view',
        extensionPoint: 'forge.views',
        label: 'Graph insights',
        view: 'graph-insights'
      }
    ]
  },
  {
    manifestVersion: 1,
    id: 'forge.backlinks',
    name: 'backlinks',
    displayName: 'Backlinks',
    description: 'Exposes local backlinks, linked mentions, and unlinked mention opportunities for the active note.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['navigation', 'organization'],
    keywords: ['backlinks', 'mentions', 'links'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:metadata',
        reason: 'Uses the local note index to find notes that link to or mention the active note.'
      }
    ],
    contributes: [
      {
        id: 'forge.backlinks.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Backlink metadata',
        fields: ['backlinks', 'backlinkCount', 'unlinkedMentions', 'unlinkedMentionCount']
      },
      {
        id: 'forge.backlinks.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Backlinks',
        widget: 'backlinks'
      },
      {
        id: 'forge.unlinked-mentions.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Unlinked mentions',
        widget: 'unlinked-mentions'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.link-health',
    name: 'link-health',
    displayName: 'Link Health',
    description: 'Surfaces unresolved wikilinks and local link health signals without running extension code.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['navigation', 'organization', 'publishing'],
    keywords: ['unresolved links', 'broken links', 'wikilinks'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:metadata',
        reason: 'Uses the local note index to compare wikilinks with known Markdown files.'
      }
    ],
    contributes: [
      {
        id: 'forge.link-health.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Unresolved link metadata',
        fields: ['resolvedLinks', 'unresolvedLinks', 'brokenLinkCount']
      },
      {
        id: 'forge.link-health.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Link health',
        widget: 'link-health'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.tag-index',
    name: 'tag-index',
    displayName: 'Tag Index',
    description: 'Exposes note tags as local metadata, sidebar chips, searchable filters, and static-publish tag pages.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['navigation', 'organization', 'publishing'],
    keywords: ['tags', 'index', 'filters'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:metadata',
        reason: 'Reads tags already parsed from Markdown bodies and frontmatter.'
      }
    ],
    contributes: [
      {
        id: 'forge.tag-index.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Tag metadata',
        fields: ['tags', 'tagCount', 'frontmatterTags', 'inlineTags']
      },
      {
        id: 'forge.tag-index.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Tags',
        widget: 'tags'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.outline-toc',
    name: 'outline-toc',
    displayName: 'Outline and Table of Contents',
    description: 'Exposes Markdown headings as a local outline and table-of-contents contribution for active notes.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['editing', 'navigation', 'organization'],
    keywords: ['outline', 'toc', 'headings'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads the active note headings already parsed by Forge.'
      }
    ],
    contributes: [
      {
        id: 'forge.outline-toc.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Heading outline metadata',
        fields: ['headings', 'headingCount', 'tableOfContents']
      },
      {
        id: 'forge.outline-toc.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Outline',
        widget: 'outline'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.task-summary',
    name: 'task-summary',
    displayName: 'Task Summary',
    description: 'Shows open, completed, and total Markdown checkbox tasks for active notes and the full vault.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['editing', 'organization'],
    keywords: ['tasks', 'checkboxes', 'todo', 'checklist'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' },
      { id: 'forge.views', label: 'Views' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads Markdown checkbox tasks already loaded from the active note.'
      }
    ],
    contributes: [
      {
        id: 'forge.task-summary.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Task metadata',
        fields: ['tasks', 'openTasks', 'completedTasks', 'taskCompletionPercent']
      },
      {
        id: 'forge.task-summary.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Task summary',
        widget: 'tasks'
      },
      {
        id: 'forge.task-summary.view',
        kind: 'view',
        extensionPoint: 'forge.views',
        label: 'Tasks view',
        view: 'tasks'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.publish-checklist',
    name: 'publish-checklist',
    displayName: 'Publish Checklist',
    description: 'Exposes local publishing readiness metadata and the built-in publish-page checklist workflow.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['publishing', 'organization'],
    keywords: ['publish', 'checklist', 'static site'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads publish-page frontmatter and checklist items from local Markdown notes.'
      }
    ],
    contributes: [
      {
        id: 'forge.publish-checklist.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Publishing checklist metadata',
        fields: ['publishStatus', 'publishSlug', 'publishChecklistItems', 'publishReady']
      },
      {
        id: 'forge.publish-checklist.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Publish checklist',
        widget: 'publish-checklist'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.frontmatter-inspector',
    name: 'frontmatter-inspector',
    displayName: 'Frontmatter Inspector',
    description: 'Exposes parsed frontmatter properties, aliases, and titles as local note metadata.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['editing', 'organization'],
    keywords: ['frontmatter', 'properties', 'metadata'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [
      { id: 'forge.note.metadata', label: 'Note metadata' },
      { id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }
    ],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads frontmatter already parsed from local Markdown notes.'
      }
    ],
    contributes: [
      {
        id: 'forge.frontmatter-inspector.metadata',
        kind: 'metadata-provider',
        extensionPoint: 'forge.note.metadata',
        label: 'Frontmatter metadata',
        fields: ['frontmatterProperties', 'aliases', 'title']
      },
      {
        id: 'forge.frontmatter-inspector.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Properties',
        widget: 'frontmatter'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  },
  {
    manifestVersion: 1,
    id: 'forge.media-player',
    name: 'media-player',
    displayName: 'Media Gallery',
    description: 'Shows linked local images, video, audio, PDFs, and common attachments from the active note.',
    version: '0.1.0',
    publisher: 'Forge',
    license: 'MIT',
    repository: 'https://github.com/forge-notes/forge',
    categories: ['capture', 'editing', 'organization'],
    keywords: ['media', 'audio', 'recordings', 'attachments', 'voice', 'gallery'],
    source: { kind: 'built-in', label: 'Bundled with Forge' },
    runtime: declarativeRuntime,
    extensionPoints: [{ id: 'forge.sidebar.widgets', label: 'Sidebar widgets' }],
    permissions: [
      {
        kind: 'vault:read',
        reason: 'Reads linked local attachments for local preview and playback.'
      }
    ],
    contributes: [
      {
        id: 'forge.media-player.gallery',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Media gallery',
        widget: 'media-gallery'
      },
      {
        id: 'forge.media-player.sidebar',
        kind: 'sidebar-widget',
        extensionPoint: 'forge.sidebar.widgets',
        label: 'Audio attachments',
        widget: 'audio'
      }
    ],
    defaultInstalled: true,
    defaultEnabled: true
  }
]

let sourceRegistryCache

function packageRoot() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
}

function extractConstArray(source, exportName) {
  const marker = `export const ${exportName}`
  const markerIndex = source.indexOf(marker)
  if (markerIndex === -1) return ''
  const assignment = source.indexOf('=', markerIndex)
  if (assignment === -1) return ''
  const start = source.indexOf('[', assignment)
  if (start === -1) return ''

  let depth = 0
  let quote = ''
  let escaped = false
  for (let index = start; index < source.length; index++) {
    const char = source[index]
    if (quote) {
      if (escaped) {
        escaped = false
      } else if (char === '\\') {
        escaped = true
      } else if (char === quote) {
        quote = ''
      }
      continue
    }

    if (char === '"' || char === "'" || char === '`') {
      quote = char
      continue
    }
    if (char === '[') depth++
    if (char === ']') {
      depth--
      if (depth === 0) return source.slice(start, index + 1)
    }
  }
  return ''
}

function readSourceRegistryCatalog() {
  if (sourceRegistryCache !== undefined) return sourceRegistryCache

  sourceRegistryCache = null
  const registryPath = path.join(packageRoot(), 'src', 'renderer', 'src', 'extensions', 'registry.ts')
  if (!fs.existsSync(registryPath)) return sourceRegistryCache

  try {
    const source = fs.readFileSync(registryPath, 'utf8')
    const pointsSource = extractConstArray(source, 'LOCAL_EXTENSION_POINTS')
    const manifestsSource = extractConstArray(source, 'LOCAL_EXTENSION_MANIFESTS')
    if (!pointsSource || !manifestsSource) return sourceRegistryCache

    const points = Function(`return (${pointsSource})`)()
    const manifests = Function('declarativeRuntime', `return (${manifestsSource})`)(declarativeRuntime)
    if (Array.isArray(points) && Array.isArray(manifests)) {
      sourceRegistryCache = { points, manifests, source: registryPath }
    }
  } catch {
    sourceRegistryCache = null
  }

  return sourceRegistryCache
}

export function extensionPointDefinitions() {
  return readSourceRegistryCatalog()?.points ?? BUILT_IN_EXTENSION_POINTS
}

export function parseTemplatePlaceholders(content) {
  const placeholders = []
  const seen = new Set()

  for (const match of content.matchAll(/\{\{\s*([^{}\n]+?)\s*\}\}/g)) {
    const raw = match[1].trim()
    const prompt = /^prompt\s*:\s*(.+)$/i.exec(raw)
    const select = /^select\s*:\s*([^|]+)(?:\|(.*))?$/i.exec(raw)
    const key = prompt?.[1]?.trim() || select?.[1]?.trim() || raw
    const kind = prompt ? 'prompt' : select ? 'select' : builtInVariableSet.has(raw.toLowerCase()) ? 'built-in' : 'custom'
    const options = select?.[2]
      ? select[2].split(/[|,]/).map((option) => option.trim()).filter(Boolean)
      : []
    const id = `${kind}:${key.toLowerCase()}:${options.join('|')}`
    if (seen.has(id)) continue
    seen.add(id)
    placeholders.push({
      key,
      kind,
      placeholder: `{{${raw}}}`,
      ...(options.length ? { options } : {})
    })
  }

  return placeholders
}

export function builtInTemplateCatalog({ includeContent = false } = {}) {
  return {
    builtInVariables: builtInTemplateVariables,
    count: BUILT_IN_STARTER_TEMPLATES.length,
    templates: BUILT_IN_STARTER_TEMPLATES.map((template) => {
      const placeholders = parseTemplatePlaceholders(template.content)
      return {
        kind: template.kind,
        label: template.label,
        detail: template.detail,
        file: template.file,
        fields: placeholders.filter((field) => field.kind !== 'built-in'),
        placeholders,
        ...(includeContent ? { content: template.content } : {})
      }
    })
  }
}

export function builtInExtensionCatalog() {
  const sourceCatalog = readSourceRegistryCatalog()
  const points = sourceCatalog?.points ?? BUILT_IN_EXTENSION_POINTS
  const manifests = sourceCatalog?.manifests ?? BUILT_IN_EXTENSION_MANIFESTS
  const contributionCount = manifests.reduce((total, manifest) => total + manifest.contributes.length, 0)
  const permissionKinds = Array.from(
    new Set(manifests.flatMap((manifest) => manifest.permissions.map((permission) => permission.kind)))
  ).sort()

  return {
    count: manifests.length,
    pointCount: points.length,
    contributionCount,
    permissionKinds,
    source: sourceCatalog ? 'source-registry' : 'script-fallback',
    points,
    manifests
  }
}
